const ScienceActivities={
 magnet(container){const b=document.getElementById(container);if(!b)return;b.innerHTML=`<div class="sim-card"><h3>🧲 चुंबक जाँच</h3><p>पहले अनुमान लगाओ—कौन-सी वस्तु चुंबक से आकर्षित होगी?</p><div class="sim-options">${[['📎','पेपर क्लिप',true],['✏️','पेंसिल',false],['🪵','लकड़ी',false],['🔩','लोहे का टुकड़ा',true]].map((x,i)=>`<button onclick="ScienceActivities.checkMagnet(${i},'${container}')"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div><div id="${container}_result" class="sim-result">एक option चुनो।</div></div>`},
 checkMagnet(i,c){const correct=[true,false,false,true][i],r=document.getElementById(c+'_result');if(!r)return;r.className='sim-result '+(correct?'sim-ok':'sim-warn');r.textContent=correct?'✅ सही! यह वस्तु सामान्यतः लौह-आधारित होने के कारण चुंबकीय आकर्षण दिखा सकती है।':'❌ अभी नहीं। केवल वस्तु का आकार/नाम देखकर नहीं—उसका material और test महत्वपूर्ण है।';this._award('magnet')},
 water(container){const b=document.getElementById(container);if(!b)return;b.innerHTML=`<div class="sim-card"><h3>💧 जल-चक्र क्रम</h3><p>नीचे processes को सही क्रम में चुनो।</p><div class="sim-sequence"><button onclick="ScienceActivities.pickWater('वाष्पीकरण','${container}')">☀️ वाष्पीकरण</button><button onclick="ScienceActivities.pickWater('संघनन','${container}')">☁️ संघनन</button><button onclick="ScienceActivities.pickWater('वर्षा','${container}')">🌧️ वर्षा</button><button onclick="ScienceActivities.pickWater('संग्रह','${container}')">🌊 संग्रह</button></div><div id="${container}_result" class="sim-result">सही क्रम: वाष्पीकरण → संघनन → वर्षा → संग्रह</div></div>`},
 waterStep:0,
 pickWater(step,c){const correct=['वाष्पीकरण','संघनन','वर्षा','संग्रह'];const r=document.getElementById(c+'_result');if(step===correct[this.waterStep]){this.waterStep++;r.className='sim-result sim-ok';r.textContent=this.waterStep===4?'🎉 पूरा क्रम सही!':'✅ सही—अब अगला step चुनो।';if(this.waterStep===4){this._award('water')}}else{this.waterStep=0;r.className='sim-result sim-warn';r.textContent='↩️ क्रम फिर से शुरू करो। पहला step = वाष्पीकरण।'}},
 separation(container){const b=document.getElementById(container);if(!b)return;b.innerHTML=`<div class="sim-card"><h3>🧺 सही separation method चुनो</h3><p>मिश्रण: <b>चावल + बड़े कंकड़</b></p><div class="sim-options"><button onclick="ScienceActivities.sep('hand','${container}')">✋ Handpicking</button><button onclick="ScienceActivities.sep('wind','${container}')">🌬️ Winnowing</button><button onclick="ScienceActivities.sep('filter','${container}')">🧺 Filtration</button></div><div id="${container}_result" class="sim-result">एक method चुनो।</div></div>`},
 sep(method,c){const r=document.getElementById(c+'_result');if(!r)return;const ok=method==='hand';r.className='sim-result '+(ok?'sim-ok':'sim-warn');r.textContent=ok?'✅ सही! बड़े, दिखाई देने वाले कंकड़ हाथ से चुने जा सकते हैं।':'❌ इस mixture के लिए handpicking अधिक direct method है।';if(ok)this._award('separation')},
 _award(key){const k='scienceActivity_'+key;if(localStorage.getItem(k))return;localStorage.setItem(k,'1');if(window.Progress)Progress.addXP(5);if(window.updateRewards)updateRewards();const t=document.createElement('div');t.className='xp-toast';t.textContent='⚡ +5 XP — Concept mastered!';document.body.appendChild(t);setTimeout(()=>t.remove(),1400)}
};