const FullScienceTest={
 active:false,questions:[],answers:{},index:0,startedAt:0,totalSeconds:0,timer:null,
 start(countPerChapter=3){const all=[];CHAPTERS.forEach(c=>{const pool=[...(c.challenge||[])];pool.sort(()=>Math.random()-.5).slice(0,countPerChapter).forEach(q=>all.push({...q,chapterId:c.id,chapterTitle:c.title}))});all.sort(()=>Math.random()-.5);this.questions=all;this.answers={};this.index=0;this.active=true;this.startedAt=Date.now();this.totalSeconds=all.length*90;clearInterval(this.timer);this.timer=setInterval(()=>this.tick(),1000);show('fullTestView');this.render();},
 tick(){if(!this.active)return;const left=this.totalSeconds-Math.floor((Date.now()-this.startedAt)/1000);const el=document.getElementById('fullTimer');if(el)el.textContent=this.format(Math.max(0,left));if(left<=0)this.finish();},
 format(sec){const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`},
 select(v){this.answers[this.index]=Number(v);this.render()},
 prev(){if(this.index>0){this.index--;this.render()}},
 next(){if(this.index<this.questions.length-1){this.index++;this.render()}else this.finish()},
 render(){const q=this.questions[this.index],box=document.getElementById('fullTestContent');if(!q||!box)return;const chosen=this.answers[this.index];const answered=Object.keys(this.answers).length;document.getElementById('fullTestProgress').style.width=((answered/this.questions.length)*100)+'%';document.getElementById('fullTestCounter').textContent=`प्रश्न ${this.index+1} / ${this.questions.length} • ${answered} answered`;const ch=document.getElementById('fullTestChapter');ch.textContent=`अध्याय ${q.chapterId} • ${q.chapterTitle}`;box.innerHTML=`<div class="full-q"><span class="qnum">${this.index+1}</span><h2>${escapeHtml(q.question)}</h2>${q.options.map((o,i)=>`<button class="full-option ${chosen===i?'selected':''}" onclick="FullScienceTest.select(${i})"><b>${String.fromCharCode(65+i)}.</b> ${escapeHtml(o)}</button>`).join('')}</div><div class="full-nav"><button class="btn soft" onclick="FullScienceTest.prev()" ${this.index===0?'disabled':''}>← पिछला</button><button class="btn primary" onclick="FullScienceTest.next()">${this.index===this.questions.length-1?'✅ Submit Test':'अगला →'}</button></div>`},
 finish(){if(!this.active)return;this.active=false;clearInterval(this.timer);let score=0;const chapter={};this.questions.forEach((q,i)=>{const ok=this.answers[i]===q.answer;if(ok)score++;chapter[q.chapterId]??={title:q.chapterTitle,score:0,total:0};chapter[q.chapterId].total++;if(ok)chapter[q.chapterId].score++});const pct=Math.round(score/Math.max(1,this.questions.length)*100);const box=document.getElementById('fullTestContent');let rows=Object.values(chapter).map(x=>`<div class="test-row"><span>${escapeHtml(x.title)}</span><b>${x.score}/${x.total}</b></div>`).join('');box.innerHTML=`<div class="test-result"><div class="quiz-score">${score}/${this.questions.length}</div><h2>${pct>=90?'🏆 शानदार प्रदर्शन!':pct>=75?'🎯 बहुत अच्छा!':pct>=50?'📚 अच्छी शुरुआत—revision करो':'🔄 concepts दोबारा पढ़ो'}</h2><p>Overall score: <b>${pct}%</b></p><div class="test-breakdown"><h3>📊 Chapter-wise performance</h3>${rows}</div><div class="nav"><button class="btn soft" onclick="goHome()">🏠 Home</button><button class="btn primary" onclick="FullScienceTest.start(3)">फिर से दें ↻</button></div></div>`;Progress.addAttempt(0,score,this.questions.length,'full-science-test');Progress.markActive();updateRewards()},
 cancel(){this.active=false;clearInterval(this.timer);show('homeView');renderHome()}
};