const FullScienceTest={
 active:false,questions:[],answers:{},index:0,startedAt:0,totalSeconds:0,timer:null,
 start(countPerChapter=4){const all=[];CHAPTERS.forEach(c=>{const pool=[...(c.challenge||[])];pool.sort(()=>Math.random()-.5).slice(0,countPerChapter).forEach(q=>all.push({...q,chapterId:c.id,chapterTitle:c.title}))});all.sort(()=>Math.random()-.5);this.questions=all;this.answers={};this.index=0;this.active=true;this.startedAt=Date.now();this.totalSeconds=all.length*90;clearInterval(this.timer);this.timer=setInterval(()=>this.tick(),1000);show('fullTestView');this.render();},
 tick(){if(!this.active)return;const left=this.totalSeconds-Math.floor((Date.now()-this.startedAt)/1000);const el=document.getElementById('fullTimer');if(el)el.textContent=this.format(Math.max(0,left));if(left<=0)this.finish(true)},
 format(sec){const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`},
 select(v){this.answers[this.index]=Number(v);this.render()},
 prev(){if(this.index>0){this.index--;this.render()}},
 next(){if(this.index<this.questions.length-1){this.index++;this.render()}else this.finish(false)},
 review(){const box=document.getElementById('fullTestContent');if(!box)return;box.innerHTML='<div id="fullReview"></div>';ExamReview.render(this.questions,this.answers,'fullReview','Full Science Test Review','<div class="nav"><button class="btn primary" onclick="FullScienceTest.render()">↩ Test result</button><button class="btn soft" onclick="FullScienceTest.start(4)">फिर से दें ↻</button></div>')},
 render(){const q=this.questions[this.index],box=document.getElementById('fullTestContent');if(!q||!box)return;const chosen=this.answers[this.index];const answered=Object.keys(this.answers).length;document.getElementById('fullTestProgress').style.width=((answered/this.questions.length)*100)+'%';document.getElementById('fullTestCounter').textContent=`प्रश्न ${this.index+1} / ${this.questions.length} • ${answered} answered`;document.getElementById('fullTestChapter').textContent=`अध्याय ${q.chapterId} • ${q.chapterTitle}`;const letters=['A','B','C','D','E'];box.innerHTML=`<div class="test-rule-bar"><span>✅ सही <b>+1</b></span><span>❌ गलत <b>0</b></span><span>⚪ छोड़ा <b>0</b></span><span>🚫 Negative <b>नहीं</b></span></div><div class="full-q"><span class="qnum">${this.index+1}</span><h2>${escapeHtml(q.question)}</h2>${q.options.map((o,i)=>`<button class="full-option ${chosen===i?'selected':''}" onclick="FullScienceTest.select(${i})"><b>${letters[i]}.</b> ${escapeHtml(o)}</button>`).join('')}</div><div class="full-nav"><button class="btn soft" onclick="FullScienceTest.prev()" ${this.index===0?'disabled':''}>← पिछला</button><button class="btn primary" onclick="FullScienceTest.next()">${this.index===this.questions.length-1?'✅ Submit Test':'अगला →'}</button></div><button class="btn soft full" onclick="FullScienceTest.openReviewPrompt()">📋 Review answers before submit</button>`},
 openReviewPrompt(){const unanswered=this.questions.filter((_,i)=>this.answers[i]===undefined).length;const ok=unanswered===0||confirm(`${unanswered} प्रश्न अभी unanswered हैं। क्या फिर भी result review देखना चाहते हैं?`);if(ok)this.renderReviewOnly()},
 renderReviewOnly(){const box=document.getElementById('fullTestContent');box.innerHTML='<div id="preReview"></div>';ExamReview.render(this.questions,this.answers,'preReview','Answer Review','<div class="nav"><button class="btn soft" onclick="FullScienceTest.render()">↩ वापस</button><button class="btn primary" onclick="FullScienceTest.finish(false)">✅ Submit Test</button></div>')},
 finish(auto=false){if(!this.active)return;this.active=false;clearInterval(this.timer);let score=0;const chapter={};this.questions.forEach((q,i)=>{const ok=Number(this.answers[i])===Number(q.answer);if(ok)score++;chapter[q.chapterId]??={title:q.chapterTitle,score:0,total:0};chapter[q.chapterId].total++;if(ok)chapter[q.chapterId].score++});const pct=Math.round(score/Math.max(1,this.questions.length)*100);const box=document.getElementById('fullTestContent');let rows=Object.values(chapter).map(x=>`<div class="test-row"><span>${escapeHtml(x.title)}</span><b>${x.score}/${x.total}</b></div>`).join('');box.innerHTML=`<div class="test-result"><span class="tag">TEST COMPLETE</span><div class="quiz-score">${score}/${this.questions.length}</div><h2>${pct>=90?'🏆 शानदार प्रदर्शन!':pct>=75?'🎯 बहुत अच्छा!':pct>=60?'📈 अच्छी प्रगति':'🔄 Revision की जरूरत है'}</h2><p>Score: <b>${pct}%</b> • ${auto?'समय समाप्त होकर auto-submit हुआ':'आपने test submit किया'}</p><div class="marking-strip"><span>✅ सही +1</span><span>❌ गलत 0</span><span>⚪ छोड़ा 0</span><span>🚫 कोई negative marking नहीं</span></div><div class="test-breakdown"><h3>📊 Chapter-wise Performance</h3>${rows}</div><div class="nav"><button class="btn primary" onclick="FullScienceTest.review()">🔎 हर प्रश्न का Review</button><button class="btn soft" onclick="FullScienceTest.start(4)">फिर से दें ↻</button></div><button class="btn soft full" onclick="goHome()">🏠 Home</button></div>`;Progress.addAttempt(0,score,this.questions.length,'full-science-test');Progress.markActive();updateRewards()},
 cancel(){this.active=false;clearInterval(this.timer);show('homeView');renderHome()}
};