window.TestInstructions=window.TestInstructions||{open({title='परीक्षा शुरू करने से पहले',subtitle='ध्यान से पढ़ें और फिर परीक्षा शुरू करें।',items=[],startLabel='परीक्षा शुरू करें 🚀'}={},onStart){if(typeof onStart!=='function')return;const old=document.getElementById('testInstructionModal');if(old)old.remove();const styleId='testInstructionStyle';if(!document.getElementById(styleId)){const s=document.createElement('style');s.id=styleId;s.textContent='.test-instruction-backdrop{position:fixed;inset:0;z-index:200;background:#071426b8;display:grid;place-items:center;padding:16px}.test-instruction-card{width:min(520px,100%);max-height:min(88vh,760px);overflow:auto;background:#fff;color:#17202a;border-radius:22px;border:1px solid #dfe5ec;box-shadow:0 25px 80px #07142655;padding:20px}.test-instruction-card h2{margin:7px 0 4px;font-size:24px}.test-instruction-card p{margin:0 0 13px;color:#667085;line-height:1.6;font-size:13px}.test-instruction-tag{display:inline-block;padding:6px 9px;border-radius:999px;background:#eef2ff;color:#3447d6;font-size:10px;font-weight:950}.test-instruction-list{display:grid;gap:8px;margin:14px 0}.test-instruction-item{display:flex;gap:9px;padding:10px 11px;border:1px solid #e2e7ec;border-radius:12px;background:#f8fafc;line-height:1.55;font-size:12px}.test-instruction-item b{min-width:20px}.test-instruction-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.test-instruction-actions button{min-height:48px;border-radius:12px;font-weight:900;cursor:pointer}.test-instruction-cancel{border:1px solid #d7dde6;background:#fff;color:#344054}.test-instruction-start{border:0;background:linear-gradient(135deg,#3447d6,#5b4bdc);color:#fff}@media(max-width:560px){.test-instruction-card{padding:16px;border-radius:18px}.test-instruction-actions{grid-template-columns:1fr}.test-instruction-card h2{font-size:21px}}';document.head.appendChild(s)}const wrap=document.createElement('div');wrap.id='testInstructionModal';wrap.className='test-instruction-backdrop';wrap.setAttribute('role','dialog');wrap.setAttribute('aria-modal','true');wrap.setAttribute('aria-labelledby','testInstructionTitle');const list=items.map((x,i)=>`<div class="test-instruction-item"><b>${i+1}.</b><span>${x}</span></div>`).join('');wrap.innerHTML=`<div class="test-instruction-card"><span class="test-instruction-tag">📌 CANDIDATE INSTRUCTIONS</span><h2 id="testInstructionTitle">${title}</h2><p>${subtitle}</p><div class="test-instruction-list">${list}</div><div class="test-instruction-actions"><button type="button" class="test-instruction-cancel">अभी नहीं</button><button type="button" class="test-instruction-start">${startLabel}</button></div></div>`;document.body.appendChild(wrap);const cancel=wrap.querySelector('.test-instruction-cancel'),start=wrap.querySelector('.test-instruction-start');cancel.onclick=()=>wrap.remove();start.onclick=()=>{wrap.remove();onStart()};wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.remove()});start.focus();}};
const FullScienceTest={
 active:false,questions:[],answers:{},index:0,startedAt:0,totalSeconds:0,timer:null,lastResult:null,
 start(countPerChapter=4){
  const begin=()=>this._start(countPerChapter);
  if(window.TestInstructions){window.TestInstructions.open({title:'12-Chapter Science Challenge',subtitle:'Exam शुरू करने से पहले instructions पढ़ लो।',items:['48 questions होंगे — 12 chapters से balanced questions.','समय 72 minutes है; timer शुरू होने के बाद चलता रहेगा.','सही उत्तर = +1 mark, गलत = 0, छोड़ा = 0; negative marking नहीं.','हर question पर answer चुनकर “अगला” दबाओ; जरूरत हो तो review answers खोलो.','Final review के बाद submit करो. समय समाप्त होने पर test auto-submit होगा.','Submit के बाद detailed question review में तुम्हारा answer, सही answer और explanation मिलेगा.'],startLabel:'Instructions पढ़ लीं — Test शुरू करें 🚀'},begin);return}begin();
 },
 _start(countPerChapter=4){
  const all=[];CHAPTERS.forEach(c=>{const pool=[...(c.challenge||[])];pool.sort(()=>Math.random()-.5).slice(0,countPerChapter).forEach(q=>all.push({...q,chapterId:c.id,chapterTitle:c.title}))});all.sort(()=>Math.random()-.5);this.questions=all;this.answers={};this.index=0;this.active=true;this.lastResult=null;this.startedAt=Date.now();this.totalSeconds=all.length*90;clearInterval(this.timer);this.timer=setInterval(()=>this.tick(),1000);show('fullTestView');this.render();
 },
 tick(){if(!this.active)return;const left=this.totalSeconds-Math.floor((Date.now()-this.startedAt)/1000);const el=document.getElementById('fullTimer');if(el)el.textContent=this.format(Math.max(0,left));if(left<=0)this.finish(true)},
 format(sec){const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`},
 select(v){if(!this.active)return;this.answers[this.index]=Number(v);this.render()},
 prev(){if(this.active&&this.index>0){this.index--;this.render()}},
 next(){if(!this.active)return;if(this.index<this.questions.length-1){this.index++;this.render()}else this.renderReviewOnly()},
 review(){if(!this.lastResult?.questions)return;const box=document.getElementById('fullTestContent');if(!box)return;box.innerHTML='<div id="fullReview"></div>';ExamReview.render(this.lastResult.questions,this.lastResult.answers,'fullReview','Full Science Test Review','<div class="nav"><button class="btn primary" onclick="FullScienceTest.showResult()">↩ Result</button><button class="btn soft" onclick="FullScienceTest.start(4)">फिर से दें ↻</button></div>')},
 render(){const q=this.questions[this.index],box=document.getElementById('fullTestContent');if(!q||!box)return;const chosen=this.answers[this.index];const answered=Object.keys(this.answers).length;if(document.getElementById('fullTestProgress'))document.getElementById('fullTestProgress').style.width=((answered/Math.max(1,this.questions.length))*100)+'%';if(document.getElementById('fullTestCounter'))document.getElementById('fullTestCounter').textContent=`प्रश्न ${this.index+1} / ${this.questions.length} • ${answered} answered`;if(document.getElementById('fullTestChapter'))document.getElementById('fullTestChapter').textContent=`अध्याय ${q.chapterId} • ${q.chapterTitle}`;const letters=['A','B','C','D','E'];box.innerHTML=`<div class="test-rule-bar"><span>✅ सही <b>+1</b></span><span>❌ गलत <b>0</b></span><span>⚪ छोड़ा <b>0</b></span><span>🚫 Negative <b>नहीं</b></span></div><div class="full-q"><span class="qnum">${this.index+1}</span><h2>${escapeHtml(q.question)}</h2>${q.options.map((o,i)=>`<button class="full-option ${chosen===i?'selected':''}" onclick="FullScienceTest.select(${i})"><b>${letters[i]}.</b> ${escapeHtml(o)}</button>`).join('')}</div><div class="full-nav"><button class="btn soft" onclick="FullScienceTest.prev()" ${this.index===0?'disabled':''}>← पिछला</button><button class="btn primary" onclick="FullScienceTest.next()">${this.index===this.questions.length-1?'📋 Final Review':'अगला →'}</button></div><button class="btn soft full" onclick="FullScienceTest.renderReviewOnly()">📋 Review answers before submit</button>`},
 openReviewPrompt(){this.renderReviewOnly()},
 renderReviewOnly(){if(!this.active)return;const box=document.getElementById('fullTestContent');if(!box)return;const unanswered=this.questions.filter((_,i)=>this.answers[i]===undefined).length;box.innerHTML=`<div id="preReview"><div class="test-rule-bar"><span>✅ Correct answers will score +1</span><span>🚫 No negative marking</span></div><h2>📋 Final Review</h2><p class="muted">${unanswered?`${unanswered} question(s) unanswered. You can still submit.`:'All questions attempted.'}</p><div class="mx-review-grid">${this.questions.map((q,i)=>`<button class="${this.answers[i]===undefined?'unanswered':''}" data-i="${i}">Q${i+1}<small>${this.answers[i]===undefined?'छोड़ा':String.fromCharCode(65+this.answers[i])}</small></button>`).join('')}</div><div class="nav"><button class="btn soft" id="fullBack">← वापस</button><button class="btn primary" id="fullSubmit">✅ Submit Test</button></div></div>`;box.querySelectorAll('.mx-review-grid button').forEach(b=>b.onclick=()=>{this.index=Number(b.dataset.i);this.render()});box.querySelector('#fullBack').onclick=()=>this.render();box.querySelector('#fullSubmit').onclick=()=>this.finish(false)},
 finish(auto=false){if(!this.active)return;this.active=false;clearInterval(this.timer);this.timer=null;let score=0;const chapter={};this.questions.forEach((q,i)=>{const ok=Number(this.answers[i])===Number(q.answer);if(ok)score++;chapter[q.chapterId]??={title:q.chapterTitle,score:0,total:0};chapter[q.chapterId].total++;if(ok)chapter[q.chapterId].score++});const pct=Math.round(score/Math.max(1,this.questions.length)*100);this.lastResult={questions:[...this.questions],answers:{...this.answers},score,total:this.questions.length,pct,auto,chapter};this.showResult();Progress.recordCompositeTest(score,this.questions.length,'full-science-test',chapter);Progress.markActive();updateRewards()},
 showResult(){const r=this.lastResult;if(!r)return;const box=document.getElementById('fullTestContent');if(!box)return;const rows=Object.values(r.chapter).map(x=>`<div class="test-row"><span>${escapeHtml(x.title)}</span><b>${x.score}/${x.total}</b></div>`).join('');box.innerHTML=`<div class="test-result"><span class="tag">TEST COMPLETE</span><div class="quiz-score">${r.score}/${r.total}</div><h2>${r.pct>=90?'🏆 शानदार प्रदर्शन!':r.pct>=75?'🎯 बहुत अच्छा!':r.pct>=60?'📈 अच्छी प्रगति':'🔄 Revision की जरूरत है'}</h2><p>Score: <b>${r.pct}%</b> • ${r.auto?'समय समाप्त होकर auto-submit हुआ':'आपने test submit किया'}</p><div class="marking-strip"><span>✅ सही +1</span><span>❌ गलत 0</span><span>⚪ छोड़ा 0</span><span>🚫 कोई negative marking नहीं</span></div><div class="test-breakdown"><h3>📊 Chapter-wise Performance</h3>${rows}</div><div class="nav"><button class="btn primary" onclick="FullScienceTest.review()">🔎 हर प्रश्न का Review</button><button class="btn soft" onclick="FullScienceTest.start(4)">फिर से दें ↻</button></div><button class="btn soft full" onclick="goHome()">🏠 Home</button></div>`},
 cancel(){this.active=false;clearInterval(this.timer);this.timer=null;this.lastResult=null;show('homeView');renderHome()}
};