(function(){'use strict';
/* Visible, resilient search layer for the unified Revision Hub. */
const norm=s=>String(s||'').toLowerCase().normalize('NFKC').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
const grams=s=>{const a=norm(s).split(' ').filter(Boolean);const out=new Set(a);a.forEach(w=>{if(w.length>3)for(let i=0;i<w.length-2;i++)out.add(w.slice(i,i+3))});return out};
const distance=(a,b)=>{if(a===b)return 0;if(!a||!b)return Math.max(a.length,b.length);if(Math.abs(a.length-b.length)>3)return 9;let p=Array(b.length+1).fill(0),q=Array(b.length+1);for(let j=0;j<=b.length;j++)p[j]=j;for(let i=1;i<=a.length;i++){q[0]=i;for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));[p,q]=[q,p]}return p[b.length]};
function score(text,query){const q=norm(query);if(!q)return 1;const t=norm(text);if(!t)return 0;let s=0;if(t===q)s+=100;if(t.includes(q))s+=70;const qw=q.split(' ').filter(Boolean),tw=t.split(' ').filter(Boolean);qw.forEach(w=>{if(tw.some(x=>x===w))s+=35;else if(tw.some(x=>x.startsWith(w)))s+=22;else if(tw.some(x=>distance(w,x)<=Math.max(1,Math.floor(w.length/4))))s+=12;});const qg=grams(q),tg=grams(t);let overlap=0;qg.forEach(g=>{if(tg.has(g))overlap++});s+=Math.min(25,overlap*2);return s};
function install(){const input=document.getElementById('urSearch');const grid=document.getElementById('urGrid');if(!input||!grid||input.dataset.smartSearch==='1')return;input.dataset.smartSearch='1';const original=input.value;const hint=document.createElement('div');hint.className='ur-search-meta';hint.setAttribute('aria-live','polite');input.insertAdjacentElement('afterend',hint);const run=()=>{const q=input.value.trim();const cards=[...grid.querySelectorAll('.ur-card')];cards.forEach(c=>{c.dataset.searchScore=String(score(c.textContent,q));c.style.display=q&&score(c.textContent,q)<=0?'none':''});if(q){const ranked=cards.map(c=>({c,s:Number(c.dataset.searchScore)||0})).sort((a,b)=>b.s-a.s);ranked.forEach(x=>grid.querySelector('.ur-grid')?.appendChild(x.c));const visible=ranked.filter(x=>x.s>0).length;hint.textContent=visible?`🔎 ${visible} result${visible===1?'':'s'} • smart/fuzzy match`:'🔎 कोई matching topic नहीं मिला — spelling या छोटा keyword आज़माओ';}else hint.textContent='🔎 Topic, chapter, subject या keyword से खोजें';};input.addEventListener('input',run);input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';run();input.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus();input.select()}});input.value=original;run();}
const boot=()=>{install();};document.addEventListener('click',e=>{if(e.target.closest('[data-sub],#urMode'))setTimeout(install,0)});const mo=new MutationObserver(()=>install());mo.observe(document.body,{childList:true,subtree:true});window.addEventListener('load',boot);setTimeout(boot,250);setTimeout(boot,1000);const style=document.createElement('style');style.textContent='.ur-search-meta{font-size:11px;color:#667085;flex:1 1 100%;margin-top:-3px;min-height:16px}.ur-search:focus{outline:3px solid rgba(32,37,43,.12);outline-offset:1px}@media(max-width:700px){.ur-search-meta{margin-top:0}}';document.head.appendChild(style);
})();
