(function(){
'use strict';
/* Final Revision owner: meaningful short content, 8 study-note cards per chapter. */
const META=[
{id:'science',icon:'🔬',hi:'विज्ञान',name:'Science',count:12},
{id:'maths',icon:'➗',hi:'गणित',name:'Maths',count:8},
{id:'english',icon:'📖',hi:'अंग्रेज़ी',name:'English',count:8},
{id:'hindi',icon:'🪔',hi:'हिंदी',name:'Hindi',count:8},
{id:'gk',icon:'🧠',hi:'सामान्य ज्ञान + तर्क',name:'GK + Reasoning',count:8},
{id:'social',icon:'🌍',hi:'सामाजिक विज्ञान',name:'Social Science',count:14}
];
const esc=s=>String(s??'').replace(/[&<>']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;'}[m]));
function subjects(){return META.map(m=>{const x=window.UnifiedRevision?.subjects?.find?.(s=>s.id===m.id);return Object.assign({},m,{units:Array.isArray(x?.units)?x.units:[]})})}
function css(){if(document.getElementById('revisionFinalCSS'))return;const s=document.createElement('style');s.id='revisionFinalCSS';s.textContent=`
#revisionView .revision-page{display:block;width:min(1180px,calc(100% - 32px));margin:24px auto 48px;box-sizing:border-box}
#revisionView .revision-page-head{display:block;width:100%;margin:0 0 18px}
#revisionView #revisionPlan,#revisionView #revisionContent{width:100%;min-width:0}
#revisionView .rf{display:grid;gap:18px;width:100%;min-width:0}
.rf-hero{padding:22px;border-radius:22px;background:linear-gradient(135deg,#20252b,#59636e);color:#fff}.rf-hero h2{margin:0 0 8px;font-size:clamp(22px,4vw,30px);line-height:1.3}.rf-hero p{margin:0;line-height:1.65;color:#e6ebef}
.rf-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.rf-stat{padding:12px;border:1px solid #ffffff22;border-radius:14px;background:#ffffff12}.rf-stat b{display:block;font-size:21px}.rf-stat span{font-size:11px;color:#d7dde3}
.rf-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.rf-sub{border:1px solid #e0e5eb;border-radius:20px;background:#fff;padding:19px;display:flex;flex-direction:column;gap:11px;box-shadow:0 8px 24px rgba(20,30,50,.07);min-width:0}.rf-icon{font-size:34px}.rf-sub h3{margin:0;line-height:1.35}.rf-muted,.rf-note{color:#667085;font-size:12px;line-height:1.6}.rf-btn{min-height:44px;border:0;border-radius:12px;padding:11px 14px;background:#20252b;color:#fff;font:inherit;font-weight:900;cursor:pointer}.rf-btn:focus-visible{outline:3px solid currentColor;outline-offset:2px}.rf-back{background:#eef2f5;color:#20252b}
.rf-chapters{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.rf-ch{border:1px solid #e0e5eb;border-radius:16px;background:#fff;padding:15px;display:flex;gap:12px;align-items:center;min-width:0}.rf-main{flex:1;min-width:0}.rf-main b{display:block;line-height:1.45}.rf-main small{display:block;margin-top:5px;color:#667085;line-height:1.5}
.rf-deck{max-width:780px;margin:auto;width:100%;display:grid;gap:14px}.rf-card{min-height:360px;perspective:1100px}.rf-face{height:360px;position:relative;transform-style:preserve-3d;transition:transform .45s;cursor:pointer}.rf-face.flip{transform:rotateY(180deg)}.rf-side{position:absolute;inset:0;backface-visibility:hidden;border:1px solid #d9dee5;border-radius:24px;padding:28px;box-sizing:border-box;background:#fff;box-shadow:0 14px 35px rgba(20,30,50,.12);display:flex;flex-direction:column;justify-content:center}.rf-side.back{transform:rotateY(180deg);background:#f8fafc}.rf-label{font-size:11px;font-weight:900;color:#667085;letter-spacing:.04em}.rf-side h2{font-size:clamp(22px,4vw,32px);line-height:1.35;margin:10px 0 14px}.rf-content{font-size:17px;line-height:1.8}.rf-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}.rf-progress{height:8px;background:#e8edf2;border-radius:99px;overflow:hidden;margin-top:14px}.rf-progress i{display:block;height:100%;background:#fff}
@media(max-width:900px){.rf-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:600px){#revisionView .revision-page{width:calc(100% - 20px);margin:14px auto 32px}.rf-grid,.rf-chapters{grid-template-columns:1fr}.rf-stats{grid-template-columns:repeat(2,1fr)}.rf-hero{padding:17px}.rf-sub{padding:16px}.rf-card,.rf-face{height:330px;min-height:330px}.rf-side{padding:21px}.rf-content{font-size:16px}.rf-actions .rf-btn{flex:1 1 130px}}
@media(prefers-reduced-motion:reduce){.rf-face{transition:none}}
`;document.head.appendChild(s)}
function open(){css();document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));const v=document.getElementById('revisionView');if(!v)return;v.classList.remove('hidden');home();window.scrollTo({top:0,behavior:'smooth'})}
function home(){const h=document.getElementById('revisionContent');if(!h)return;const ss=subjects();h.innerHTML=`<div class="rf"><div class="rf-hero"><h2>🧠 Smart Revision Hub</h2><p>हर chapter को 8 छोटे, अर्थपूर्ण study notes में revise करो — definition, key fact, explanation, example, connection, caution, application और exam recap.</p><div class="rf-stats"><div class="rf-stat"><b>${ss.length}</b><span>Subjects</span></div><div class="rf-stat"><b>${ss.reduce((n,s)=>n+s.count,0)}</b><span>Chapters</span></div><div class="rf-stat"><b>8</b><span>Cards / chapter</span></div><div class="rf-stat"><b>${ss.reduce((n,s)=>n+s.count*8,0)}</b><span>Total cards</span></div></div></div><div class="rf-grid">${ss.map(s=>`<article class="rf-sub"><span class="rf-icon">${s.icon}</span><h3>${esc(s.hi)}</h3><div class="rf-muted">${esc(s.name)} • ${s.count} chapters • ${s.count*8} cards</div><div class="rf-muted">Definitions • key facts • examples • connections • applications • exam recap</div><button class="rf-btn" data-s="${s.id}">Open subject →</button></article>`).join('')}</div></div>`;h.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>chapters(b.dataset.s))}
function chapters(id){const s=subjects().find(x=>x.id===id),h=document.getElementById('revisionContent');if(!s||!h)return;h.innerHTML=`<div class="rf"><button class="rf-btn rf-back" id="rfBack">← सभी subjects</button><div class="rf-hero"><h2>${s.icon} ${esc(s.hi)}</h2><p>${s.count} chapters • हर chapter में 8 meaningful revision cards</p></div><div class="rf-chapters">${Array.from({length:s.count},(_,i)=>{const u=s.units[i]||['Chapter '+(i+1),'इस chapter का मुख्य विचार याद करो।','एक सरल example से concept को जोड़ो।'];return `<article class="rf-ch"><span class="rf-icon">🃏</span><div class="rf-main"><b>Chapter ${i+1} · ${esc(u[0])}</b><small>${esc(u[1])}</small></div><button class="rf-btn" data-c="${i}">Revise</button></article>`}).join('')}</div></div>`;document.getElementById('rfBack').onclick=home;h.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>deck(s,+b.dataset.c))}
function makeCards(u){
 const t=u[0]||'Chapter',a=u[1]||'इस chapter का मुख्य विचार समझो।',b=u[2]||'इस विचार को एक उदाहरण से जोड़ो।';
 return [
 ['🎯 मुख्य विचार',`इस chapter का केंद्रीय विचार: ${a}`,`मुख्य बात: ${a}`],
 ['⭐ जरूरी तथ्य',`याद रखने योग्य तथ्य: ${b}`,`Exam point: ${b}`],
 ['💡 सरल समझ',`${t} को सरल शब्दों में समझें: ${a}`,`सरल सार: ${a} ${b}`],
 ['🏠 वास्तविक उदाहरण',`दैनिक जीवन से जुड़ाव: ${b}`,`Example connection: ${b}`],
 ['🔗 संबंध',`${a} और ${b} मिलकर इस topic की पूरी समझ बनाते हैं।`,`Concept link: ${a} इसलिए ${b}`],
 ['⚠️ महत्वपूर्ण सावधानी',`इस topic में केवल शब्द याद करने के बजाय concept का अर्थ और उसका उपयोग समझना जरूरी है।`,`ध्यान रखें: ${a} को ${b} से जोड़कर पढ़ें।`],
 ['🚀 उपयोग',`इस knowledge का उपयोग नई situation में करने के लिए पहले ${t} का मुख्य concept पहचानें।`,`Application idea: ${b}`],
 ['📝 Exam recap',`Exam revision के लिए ${t} की सबसे जरूरी बातें: ${a} ${b}`,`Quick recap: ${a} ${b}`]
 ];
}
function deck(s,i){const u=s.units[i]||['Chapter '+(i+1),'इस chapter का मुख्य विचार याद करो।','एक सरल example से concept को जोड़ो।'];const cards=makeCards(u);let p=0,flip=false;const h=document.getElementById('revisionContent');function paint(){const c=cards[p];h.innerHTML=`<div class="rf"><div class="rf-deck"><button class="rf-btn rf-back" id="rfCh">← Chapters</button><div class="rf-hero"><h2>${s.icon} ${esc(s.hi)} · Chapter ${i+1}</h2><p>${esc(u[0])} • Card ${p+1} / ${cards.length}</p><div class="rf-progress"><i style="width:${(p+1)/cards.length*100}%"></i></div></div><div class="rf-card"><div id="rfFace" class="rf-face ${flip?'flip':''}" tabindex="0" role="button" aria-label="Flashcard flip करें"><div class="rf-side"><div class="rf-label">${esc(c[0])}</div><h2>${esc(c[1])}</h2><div class="rf-content">यह एक short study note है। पहले इसे ध्यान से पढ़ो, फिर अपने शब्दों में दोहराओ।</div></div><div class="rf-side back"><div class="rf-label">STUDY RECAP</div><div class="rf-content">${esc(c[2])}</div><div class="rf-note">अब इस बात को अपनी भाषा में एक बार दोहराओ।</div></div></div></div><div class="rf-actions"><button class="rf-btn rf-back" id="rfPrev" ${p?'':'disabled'}>← Previous</button><button class="rf-btn" id="rfNext">${p===cards.length-1?'Finish':'Next →'}</button></div><div class="rf-note">Card ${p+1}/${cards.length} • Read → Understand → Flip → Recall</div></div></div>`;document.getElementById('rfCh').onclick=()=>chapters(s.id);const f=document.getElementById('rfFace');f.onclick=()=>{flip=!flip;paint()};f.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip=!flip;paint()}};f.focus();document.getElementById('rfPrev').onclick=()=>{if(p){p--;flip=false;paint()}};document.getElementById('rfNext').onclick=()=>{if(p<cards.length-1){p++;flip=false;paint()}else{let d={};try{d=JSON.parse(localStorage.getItem('class6RevisionContent')||'{}')}catch(_){}d[s.id+':'+i]=Date.now();localStorage.setItem('class6RevisionContent',JSON.stringify(d));chapters(s.id)}}}paint()}
window.openUnifiedRevision=open;window.openRevision=open;window.RevisionFinal={open,home,chapters};
})();
