window.ExamReview={
 _safe(s){return window.escapeHtml?escapeHtml(s):String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))},
 _findSection(q){const c=window.CHAPTERS?.find(x=>x.id===Number(q.chapterId))||window.CHAPTERS?.find(x=>x.id===Number(window.currentChapter));if(!c)return null;const words=String(q.question+' '+(q.options?.[q.answer]||'')).toLowerCase().split(/\s+/).filter(w=>w.length>2);let best=null,score=0;(c.sections||[]).forEach(s=>{const text=(s.title+' '+s.body+' '+(s.remember||'')).toLowerCase();const n=words.reduce((v,w)=>v+(text.includes(w)?1:0),0);if(n>score){score=n;best=s}});return best},
 explanation(q){if(q.explanation)return q.explanation;const s=this._findSection(q);if(s?.remember)return s.remember;return s?.body?.split('।')[0]||'सही उत्तर को chapter के मुख्य concept से जोड़कर समझना जरूरी है।'},
 example(q){if(q.example)return q.example;const t=(q.question+' '+(q.options?.[q.answer]||'')).toLowerCase();const examples=[
 [/पानी|जल|वाष्प|evaporation|boiling|condensation/,'जैसे गीले कपड़े का सूखना वाष्पीकरण से जुड़ा है और ठंडी बोतल के बाहर बूंदें संघनन से बन सकती हैं।'],
 [/चुंबक|magnet|ध्रुव|pole/,'जैसे चुंबक लोहे की वस्तु को आकर्षित कर सकता है, लेकिन हर धातु चुंबकीय नहीं होती।'],
 [/माप|measurement|लंबाई|तापमान|thermometer/,'जैसे कमरे का तापमान thermometer से मापकर संख्या के रूप में दर्ज किया जा सकता है।'],
 [/पृथक्करण|filter|छन|sieving|winnow|निथार|नमक/,'जैसे चाय से पत्तियाँ छान सकते हैं, जबकि नमक-पानी से नमक पाने के लिए वाष्पीकरण उपयोगी हो सकता है।'],
 [/जीव|living|respiration|श्वसन|वृद्धि|प्रजनन/,'जैसे पौधा स्थिर दिखाई देने पर भी उसमें वृद्धि और श्वसन जैसी जीवन-प्रक्रियाएँ चलती रहती हैं।'],
 [/सूर्य|चंद्रमा|ग्रह|तारा|सौरमंडल|नक्षत्र/,'जैसे चंद्रमा सूर्य का प्रकाश परावर्तित करता है, जबकि सूर्य स्वयं एक तारा है।'],
 [/आकाश|प्रकाश|छाया|अवलोकन|प्रयोग|प्रमाण/,'जैसे किसी वस्तु का आकार अलग-अलग दूरी पर मापकर observation को data के रूप में दर्ज किया जा सकता है।']
 ];for(const [re,e] of examples)if(re.test(t))return e;const s=this._findSection(q);return s?`इस concept का उदाहरण: ${s.body.split('।')[0]}।`:'रोज़मर्रा की किसी ऐसी स्थिति को खोजो जिसमें यही नियम दिखाई दे।';},
 render(questions,answers,containerId,title='Question-wise Review',backHtml=''){
  const box=document.getElementById(containerId);if(!box)return;let score=0,total=0;const cards=questions.map((q,i)=>{const chosen=answers?.[i];const has=chosen!==undefined&&chosen!==null;const ok=has&&Number(chosen)===Number(q.answer);if(ok)score++;total++;const status=ok?'correct':has?'incorrect':'unanswered';return `<details class="review-card ${status}" ${i<2?'open':''}><summary><span class="review-num">${i+1}</span><span class="review-title">${this._safe(q.question)}</span><span class="review-status">${ok?'✅ सही':has?'❌ गलत':'⚪ छोड़ा'}</span></summary><div class="review-body"><div class="review-answer-grid"><div><small>आपका उत्तर</small><b>${has?this._safe(q.options[Number(chosen)]):'उत्तर नहीं दिया'}</b></div><div><small>सही उत्तर</small><b>${this._safe(q.options[q.answer])}</b></div></div><div class="review-why"><b>💡 क्यों?</b><p>${this._safe(this.explanation(q))}</p></div><div class="review-example"><b>🌍 उदाहरण</b><p>${this._safe(this.example(q))}</p></div></div></details>`}).join('');const pct=Math.round(score/Math.max(1,total)*100);box.innerHTML=`<div class="review-head"><div><span class="tag">${this._safe(title)}</span><h2>हर प्रश्न का Review</h2><p class="muted">सही, गलत और छोड़े गए सभी प्रश्नों को समझो।</p></div><div class="review-score"><b>${score}/${total}</b><span>${pct}%</span></div></div><div class="marking-strip"><span>✅ सही: <b>+1</b></span><span>❌ गलत: <b>0</b></span><span>⚪ छोड़ा: <b>0</b></span><span>🚫 Negative: <b>नहीं</b></span></div>${cards}${backHtml}`
 }
};