(function(){
'use strict';

const KEY='class6XPSystemV1';
const SUBJECTS=['science','maths','english','hindi','gk','social','revision'];
const DAILY_CAP=200;
const ACTIVITY_SOURCE='xp-system-v2';
const BADGES=[
{id:'xp-100',xp:100,icon:'🌱',title:'First Steps',text:'You reached 100 unified XP across the learning hub.'},
{id:'xp-300',xp:300,icon:'🚀',title:'Learning Explorer',text:'You reached 300 unified XP. Keep exploring every subject.'},
{id:'xp-600',xp:600,icon:'🎓',title:'Dedicated Learner',text:'You reached 600 unified XP through consistent study.'},
{id:'xp-1000',xp:1000,icon:'🏆',title:'Knowledge Achiever',text:'You reached 1,000 unified XP across your subjects.'},
{id:'xp-1500',xp:1500,icon:'👑',title:'Learning Master',text:'You reached 1,500 XP. Excellent progress.'}
];
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,Number(n)||0));
const dayKey=(value)=>{const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return null;return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const today=()=>dayKey(new Date());
const defaults=()=>({version:1,total:0,subjects:{science:0,maths:0,english:0,hindi:0,gk:0,social:0,revision:0},events:[],daily:{date:today(),earned:0},activeDays:[],legacySeeded:false});
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.version===1)return Object.assign(defaults(),x,{subjects:Object.assign(defaults().subjects,x.subjects||{}),events:Array.isArray(x.events)?x.events:[],daily:x.daily&&typeof x.daily==='object'?x.daily:defaults().daily,activeDays:Array.isArray(x.activeDays)?[...new Set(x.activeDays.map(dayKey).filter(Boolean))].sort().slice(-400):[]});}catch(_){}return defaults()}
let state=read();
function save(){state.activeDays=[...new Set((Array.isArray(state.activeDays)?state.activeDays:[]).map(dayKey).filter(Boolean))].sort().slice(-400);localStorage.setItem(KEY,JSON.stringify(state));return state}
function resetDaily(){const d=today();if(state.daily?.date!==d)state.daily={date:d,earned:0}}
function recordActivity(){const d=today();if(!state.activeDays.includes(d))state.activeDays.push(d);state.activeDays.sort();state.activeDays=state.activeDays.slice(-400);resetDaily()}
function activityDays(){return [...state.activeDays]}
function currentStreak(){const days=new Set(state.activeDays);let cursor=new Date(),streak=0;while(days.has(dayKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1)}return streak}
function legacyValue(key){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(!x)return 0;if(Array.isArray(x)){return x.reduce((s,v)=>s+10+(Number(v.score)||0)*2,0)}return Math.max(0,Number(x.xp)||0)}catch(_){return 0}}
function legacySnapshot(){return{science:legacyValue('class6ScienceProgressV9'),maths:legacyValue('mathsExamHistory'),english:legacyValue('class6EnglishProgressV1'),hindi:legacyValue('class6HindiProgressV2'),gk:legacyValue('class6GKProgressV1'),social:legacyValue('socialScienceProgressV3'),revision:legacyValue('class6RevisionProgressV1')}}
function seedLegacy(){if(state.legacySeeded)return;const legacy=legacySnapshot();state.total=0;Object.keys(state.subjects).forEach(s=>{const v=Math.max(0,Math.round(legacy[s]||0));state.subjects[s]=v;state.total+=v});state.legacySeeded=true;state.daily={date:today(),earned:0};save()}
function reconcileLegacy(){const legacy=legacySnapshot();let changed=false;Object.keys(state.subjects).forEach(s=>{const v=Math.max(0,Math.round(legacy[s]||0));if(v>Number(state.subjects[s]||0)){state.subjects[s]=v;changed=true}});if(changed){state.total=Object.values(state.subjects).reduce((sum,v)=>sum+Math.max(0,Number(v)||0),0);save()}return changed}
seedLegacy();
reconcileLegacy();
function multiplier(subject,content){const n=state.events.filter(e=>e.subject===subject&&e.content===String(content||'')).length;return n===0?1:n===1?.6:n===2?.3:.1}
function attemptXP(pct){return 5+Math.round(clamp(pct)*.25)}
function badgeSnapshot(xp=state.total){return BADGES.filter(b=>Number(xp)>=b.xp).map(b=>Object.assign({},b))}
function nextBadge(xp=state.total){return BADGES.find(b=>Number(xp)<b.xp)||null}
function injectBadgeUI(){const view=document.getElementById('progressView');if(!view||document.getElementById('unifiedXPBadges'))return;const style=document.createElement('style');style.id='unifiedXPBadgesStyle';style.textContent='.unified-xp-badges{margin:0 0 22px;padding:18px;border:1px solid #dbe4ee;border-radius:20px;background:linear-gradient(180deg,#fff,#f8fbff);box-shadow:0 10px 28px rgba(15,23,42,.06)}.unified-xp-badges-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px}.unified-xp-badges-head h2{margin:0;font-size:20px}.unified-xp-badges-head span{font-size:12px;color:#64748b}.unified-xp-badge-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.unified-xp-badge{border:1px solid #e2e8f0;border-radius:16px;padding:13px;text-align:center;background:#fff;min-height:110px;display:flex;flex-direction:column;justify-content:center}.unified-xp-badge.locked{opacity:.48;filter:grayscale(.45)}.unified-xp-badge-icon{font-size:28px;line-height:1.1}.unified-xp-badge-title{font-weight:700;font-size:13px;margin-top:7px}.unified-xp-badge-xp{font-size:11px;color:#64748b;margin-top:4px}@media(max-width:900px){.unified-xp-badge-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:600px){.unified-xp-badges{padding:14px;border-radius:18px}.unified-xp-badges-head{align-items:flex-start;flex-direction:column;gap:4px}.unified-xp-badge-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.unified-xp-badge{min-height:100px;padding:11px}.unified-xp-badge-icon{font-size:25px}}';if(!document.getElementById('unifiedXPBadgesStyle'))document.head.appendChild(style);const section=document.createElement('section');section.id='unifiedXPBadges';section.className='unified-xp-badges';section.innerHTML='<div class="unified-xp-badges-head"><h2>🏆 XP Badges</h2><span>Unlocked from your shared XP total</span></div><div class="unified-xp-badge-grid"></div>';view.querySelector('.lesson-head')?.insertAdjacentElement('afterend',section);if(!section.parentNode)view.appendChild(section);renderBadgeUI()}
function renderBadgeUI(){const section=document.getElementById('unifiedXPBadges');if(!section)return;const grid=section.querySelector('.unified-xp-badge-grid');if(!grid)return;grid.innerHTML=BADGES.map(b=>`<article class="unified-xp-badge ${state.total>=b.xp?'unlocked':'locked'}"><div class="unified-xp-badge-icon">${state.total>=b.xp?b.icon:'🔒'}</div><div class="unified-xp-badge-title">${b.title}</div><div class="unified-xp-badge-xp">${b.xp.toLocaleString()} XP</div></article>`).join('')}
function showUnifiedBadgePopup(b){if(!b)return;let modal=document.getElementById('badgeModal');if(modal){const icon=document.getElementById('badgeIcon'),title=document.getElementById('badgeTitle'),text=document.getElementById('badgeText');if(icon)icon.textContent=b.icon||'🏆';if(title)title.textContent=b.title||'नई उपलब्धि!';if(text)text.textContent=b.text||'तुमने एक नया learning milestone unlock किया!';modal.classList.remove('hidden');setTimeout(()=>modal.classList.add('show'),20);return}modal=document.createElement('div');modal.id='unifiedXPBadgeModal';modal.className='modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.innerHTML=`<div class="modal-card"><div class="unlock-icon">${b.icon||'🏆'}</div><span class="tag">BADGE UNLOCKED</span><h2>${b.title||'नई उपलब्धि!'}</h2><p class="muted">${b.text||'तुमने एक नया learning milestone unlock किया!'}</p><button class="btn primary full" type="button">आगे बढ़ें 🚀</button></div>`;document.body.appendChild(modal);const close=()=>{modal.classList.remove('show');setTimeout(()=>modal.remove(),180)};modal.querySelector('button')?.addEventListener('click',close);setTimeout(()=>modal.classList.add('show'),20)}
function award(subject,action,content,points,meta={}){subject=SUBJECTS.includes(subject)?subject:null;if(!subject)return{awarded:0,total:state.total,subjectTotal:0,reason:'invalid-subject'};const key=`${subject}|${action}|${String(content||'')}`;if(state.events.some(e=>e.key===key&&meta.once!==false))return{awarded:0,total:state.total,subjectTotal:state.subjects[subject],reason:'duplicate'};let base=Math.max(0,Math.round(Number(points)||0));if(meta.diminishing!==false)base=Math.round(base*multiplier(subject,content));resetDaily();recordActivity();const remaining=Math.max(0,DAILY_CAP-(Number(state.daily.earned)||0));const value=Math.min(base,remaining);if(value<=0){save();return{awarded:0,total:state.total,subjectTotal:state.subjects[subject],reason:'daily-cap'}}const beforeBadges=badgeSnapshot(state.total);state.subjects[subject]+=value;state.total+=value;state.daily.earned+=value;state.events.unshift({id:`xp_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,key,subject,action,content:String(content||''),points:value,at:new Date().toISOString()});state.events=state.events.slice(0,500);save();const afterBadges=badgeSnapshot(state.total);const unlocked=afterBadges.filter(a=>!beforeBadges.some(b=>b.id===a.id));window.dispatchEvent(new CustomEvent('xp:earned',{detail:{subject,action,points:value,total:state.total,subjectTotal:state.subjects[subject],dailyEarned:state.daily.earned,activeDays:state.activeDays.length,badges:afterBadges,unlockedBadges:unlocked}}));unlocked.forEach(b=>window.dispatchEvent(new CustomEvent('xp:badge-unlocked',{detail:b})));renderBadgeUI();return{awarded:value,total:state.total,subjectTotal:state.subjects[subject],reason:'awarded',unlockedBadges:unlocked}}
function score(subject,content,pct,kind='attempt'){return award(subject,kind,content,attemptXP(pct),{diminishing:true,once:false})}
function level(xp=state.total){let level=1,need=100;while(xp>=need){xp-=need;level++;need=100+((level-1)*50)}return{level,xpIntoLevel:xp,nextLevelXP:need,title:level>=10?'Master':level>=7?'Achiever':level>=5?'Scholar':level>=3?'Explorer':'Learner'}}
function snapshot(){const badges=badgeSnapshot();return{total:state.total,subjects:Object.assign({},state.subjects),daily:Object.assign({},state.daily),activeDays:[...state.activeDays],events:state.events.length,level:level(),badges,nextBadge:nextBadge(),activitySource:ACTIVITY_SOURCE}}
function recordLearningDay(reason='learning'){recordActivity();save();const detail={date:today(),activeDays:[...state.activeDays],streak:currentStreak(),reason,source:ACTIVITY_SOURCE};window.dispatchEvent(new CustomEvent('xp:activity',{detail}));return detail}
window.XPSystem={KEY,DAILY_CAP,BADGES,ACTIVITY_SOURCE,read:()=>state,save,seedLegacy,reconcileLegacy,award,score,attemptXP,level,badges:()=>badgeSnapshot(),nextBadge:()=>nextBadge(),snapshot,recordLearningDay,recordActivity,activityDays,currentStreak};
window.addEventListener('xp:badge-unlocked',e=>showUnifiedBadgePopup(e.detail));
window.addEventListener('DOMContentLoaded',()=>{injectBadgeUI();renderBadgeUI()});
})();