const GK_TOPICS=[
{id:1,title:'India & Civics',icon:'🇮🇳',lessons:[['National Symbols','Learn the national flag, emblem, anthem and other important symbols of India.','The Ashoka Chakra on the national flag has 24 spokes.'],['States, Capitals & UTs','Learn selected states, capitals and Union Territories with map awareness.','Bihar → Patna; Rajasthan → Jaipur.'],['Government Basics','Understand simple roles of the President, Prime Minister, Parliament and courts.','Parliament makes laws at the national level.']],questions:[['The capital of India is…',['Mumbai','New Delhi','Kolkata','Chennai'],1],['The Ashoka Chakra has how many spokes?',['12','18','24','32'],2],['Which is a Union Territory?',['Bihar','Goa','Delhi','Assam'],2]]},
{id:2,title:'Geography & Environment',icon:'🌍',lessons:[['Continents & Oceans','Know the major continents and oceans and their broad locations.','Asia is the largest continent.'],['Landforms','Mountains, plateaus, plains, deserts, valleys and islands have different features.','A plateau is elevated land with a relatively flat top.'],['Environment','Air, water, soil, forests and wildlife are parts of our environment.','Planting trees helps protect soil and habitats.']],questions:[['The largest continent is…',['Africa','Asia','Europe','Australia'],1],['A flat-topped elevated landform is a…',['valley','plateau','island','delta'],1],['Which helps reduce soil erosion?',['Removing all plants','Planting vegetation','Burning forests','Leaving soil bare'],1]]},
{id:3,title:'Science Around Us',icon:'🔬',lessons:[['Everyday Science','Use scientific thinking to explain common observations around us.','A metal spoon feels hot after staying in hot tea because heat transfers to it.'],['Human Body Basics','Know simple functions of major organs and body systems.','The heart pumps blood around the body.'],['Space & Earth','Learn basic facts about the Sun, Moon, Earth and the solar system.','Earth revolves around the Sun and the Moon revolves around Earth.']],questions:[['Which organ pumps blood?',['Lungs','Heart','Stomach','Kidney'],1],['Earth is a…',['star','planet','satellite','comet'],1],['The Moon is Earth’s natural…',['planet','star','satellite','asteroid'],2]]},
{id:4,title:'History & Culture',icon:'🏛️',lessons:[['Ancient India','Know major ideas and achievements from ancient Indian history without memorizing long lists.','The Indus Valley Civilization is known for planned cities.'],['Important Personalities','Learn contributions of selected Indian and world personalities.','Mahatma Gandhi is associated with non-violent resistance.'],['Art, Festivals & Heritage','India has diverse languages, dances, food traditions, festivals and monuments.','Different regions of India have distinct cultural traditions.']],questions:[['The Indus Valley Civilization is famous for…',['planned cities','modern airplanes','space stations','printing presses'],0],['Gandhi is strongly associated with…',['non-violence','steam engines','astronomy only','painting'],0],['A monument of historical importance is part of…',['heritage','weather','arithmetic','biology'],0]]},
{id:5,title:'World GK',icon:'🌐',lessons:[['Countries & Capitals','Learn common country-capital pairs and use elimination when unsure.','Japan → Tokyo; France → Paris.'],['World Records in Geography','Know broad facts such as largest ocean and highest mountain.','Pacific Ocean is the largest ocean.'],['International Organisations','Recognize basic roles of organisations such as the United Nations.','The UN works on international cooperation and peace.']],questions:[['Capital of Japan is…',['Seoul','Tokyo','Beijing','Bangkok'],1],['Largest ocean is…',['Atlantic','Indian','Pacific','Arctic'],2],['UN stands for…',['United Nations','Universal Network','United Neighbours','United News'],0]]},
{id:6,title:'Sports & Games',icon:'🏅',lessons:[['Major Sports','Identify popular sports and their basic terminology.','A wicket is an important term in cricket.'],['Olympics','Learn why the Olympic Games are held and recognise common symbols.','The Olympic Games bring athletes from many countries together.'],['Sportsmanship','Winning matters, but fairness, discipline and respect matter too.','Following rules and respecting opponents are signs of sportsmanship.']],questions:[['Which sport uses a wicket?',['Football','Cricket','Tennis','Swimming'],1],['The Olympics involve athletes from…',['one city only','many countries','one school','one team only'],1],['Fair play means…',['breaking rules','respecting rules and opponents','always winning','avoiding practice'],1]]},
{id:7,title:'Vocabulary & Current Awareness Basics',icon:'🧠',lessons:[['Useful GK Words','Build a strong bank of common terms: democracy, habitat, currency, invention and more.','Currency means the money used in a country.'],['Fact vs Guess','Separate information you know from assumptions. Check clues before answering.','If a question gives a map, use its labels rather than guessing from memory.'],['Smart Learning Habit','Review mistakes and connect facts with places, people or ideas.','Link a capital to its state instead of memorising the pair in isolation.']],questions:[['Currency means…',['a type of weather','money used in a country','a mountain','a festival'],1],['A fact is…',['an unsupported guess','information that can be checked','a random opinion','always a prediction'],1],['A good GK strategy is to…',['guess every time','connect and review facts','skip every hard question','memorise without understanding'],1]]}
];
const REASONING_QUESTIONS=[
['Find the next number: 2, 4, 8, 16, __',['18','24','32','34'],2],
['Odd one out: Apple, Mango, Potato, Banana',['Apple','Mango','Potato','Banana'],2],
['If CAT is coded as DBU, DOG is coded as…',['EPH','EOH','DPG','FPI'],0],
['Complete the analogy: Bird : Nest :: Bee : __',['Hive','Leaf','Hole','Web'],0],
['A clock shows 3:00. The angle between the hands is…',['30°','60°','90°','180°'],2],
['Find the missing letter: A, C, E, G, __',['H','I','J','K'],1],
['Ravi is taller than Aman. Aman is taller than Mohan. Who is shortest?',['Ravi','Aman','Mohan','Cannot say'],2],
['If Monday is coded 1 and Tuesday 2, Wednesday is…',['2','3','4','5'],1],
['Which number does not belong? 3, 6, 9, 11, 12',['3','6','11','12'],2],
['A book is to reading as a fork is to…',['writing','eating','drawing','sleeping'],1],
['Complete: 5, 10, 20, 40, __',['50','60','70','80'],3],
['Which shape has exactly three sides?',['Square','Triangle','Circle','Rectangle'],1],
['If all roses are flowers and some flowers are red, which must be true?',['All roses are red','Roses are flowers','All red things are roses','No rose is red'],1],
['A boy walks north, then turns right. He is now facing…',['West','East','South','North'],1],
['Arrange from smallest to largest: 0.5, 0.05, 0.55',['0.05, 0.5, 0.55','0.5, 0.05, 0.55','0.55, 0.5, 0.05','0.05, 0.55, 0.5'],0]
];
window.GK_TOPICS=GK_TOPICS;
window.REASONING_QUESTIONS=REASONING_QUESTIONS;
