window.chapter09={
 id:9,title:"दैनिक जीवन में पृथक्करण की विधियाँ",icon:"🧺",
 goal:"मिश्रण पहचानना, घटकों के गुणों के आधार पर उपयुक्त पृथक्करण विधि चुनना, छंटाई, फटकना, छनन, तलछटीकरण, निथारना, वाष्पीकरण और दैनिक जीवन के उपयोग को reasoning के साथ समझना।",
 sections:[
 {title:"🌟 पृथक्करण की जरूरत क्यों पड़ती है?",body:"हमारे आसपास कई पदार्थ मिश्रण के रूप में मिलते हैं। चावल में छोटे कंकड़, दाल में बाहरी कण, चाय में पत्तियाँ और नमक मिले पानी जैसे उदाहरण दिखाते हैं कि कभी-कभी मिश्रण के अलग-अलग घटकों को अलग करना जरूरी होता है। कारण हो सकता है—अनचाही चीज़ हटाना, उपयोगी पदार्थ पाना या पदार्थ को अधिक उपयुक्त रूप में प्राप्त करना।",remember:"Separation का तरीका मिश्रण के components और उनके गुणों पर निर्भर करता है।",activity:"रसोई में मिलने वाले तीन मिश्रण लिखो और सोचो कि उन्हें अलग करने की जरूरत क्यों पड़ सकती है।",visual:["🍚","🪨","🧺"],visualText:["मिश्रण","अनचाहा घटक","अलग करना"],think:"क्या हर मिश्रण को हाथ से अलग किया जा सकता है? क्यों नहीं?"},
 {title:"👀 मिश्रण को पहले पहचानो",body:"किसी भी separation method को चुनने से पहले यह देखना चाहिए कि मिश्रण में कौन-कौन से components हैं। क्या वे दिखाई देते हैं? क्या एक ठोस है और दूसरा द्रव? क्या particles के size में अंतर है? क्या कोई पदार्थ पानी में घुलता है? इन्हीं गुणों से method चुनने का निर्णय मजबूत बनता है।",remember:"पहले पहचानो → फिर गुण देखो → फिर method चुनो।",activity:"मिश्रण के components की सूची बनाकर हर एक का एक relevant property लिखो।"},
 {title:"✋ हाथ से छंटाई (Handpicking)",body:"जब मिश्रण के अनचाहे घटक आसानी से दिखाई दें और उन्हें हाथ से उठाकर अलग किया जा सके, तब handpicking उपयोगी हो सकती है। चावल या दाल में बड़े कंकड़ हटाना इसका परिचित उदाहरण है। यह method छोटे और बहुत सारे unseen particles के लिए practical नहीं होती।",remember:"Visible + अलग size/appearance + कम मात्रा → handpicking उपयोगी हो सकती है।",visual:["🍚","🪨","✋"],visualText:["चावल","कंकड़","हाथ से अलग"],think:"यदि कंकड़ इतने छोटे हों कि दिखाई ही न दें, तो handpicking की limitation क्या होगी?"},
 {title:"🌬️ फटकना (Winnowing)",body:"Winnowing में हवा की मदद से हल्के और भारी components को अलग करने की कोशिश की जाती है। खेती में अनाज और हल्की भूसी अलग करने का पारंपरिक उदाहरण प्रसिद्ध है। हवा हल्के हिस्से को अपेक्षाकृत दूर ले जा सकती है जबकि भारी grains नीचे गिरते हैं।",remember:"Winnowing = हवा + अलग masses/weight behavior वाले हल्के-भारी components।",activity:"बिना वास्तविक अनाज उड़ाए, एक diagram बनाओ जिसमें हवा की दिशा और हल्के/भारी कणों का रास्ता दिखाओ।",visual:["🌾","💨","🥣"],visualText:["अनाज+भूसी","हवा","अलग"],mistake:"गलती: हर दो solid पदार्थों को winnowing से अलग किया जा सकता है—नहीं; हल्के और भारी components के व्यवहार में उपयुक्त अंतर चाहिए।"},
 {title:"🕳️ छलनी से छनन / Sieving",body:"जब ठोस particles के आकार में पर्याप्त अंतर हो, तो sieve का उपयोग करके छोटे particles को छेदों से गुजरने और बड़े particles को रोकने में मदद मिल सकती है। आटा छानना एक सामान्य उदाहरण है।",remember:"Sieving मुख्यतः particle size के अंतर का उपयोग करता है।",visual:["🌾","🕳️","🥣"],visualText:["मिश्रण","छलनी","अलग कण"],think:"यदि दोनों materials के particles लगभग समान size के हों, तो sieving क्यों काम नहीं करेगी?"},
 {title:"💧 तलछटीकरण (Sedimentation)",body:"यदि किसी ठोस के भारी particles द्रव में घुले नहीं हैं और समय के साथ नीचे बैठ जाते हैं, तो इस प्रक्रिया को sedimentation कहा जा सकता है। उदाहरण: गंदे पानी में मिट्टी के कुछ कण नीचे जमा हो सकते हैं।",remember:"Heavy insoluble particles → समय के साथ नीचे बैठ सकते हैं।",activity:"एक गिलास साफ पानी में मिट्टी डालने का वास्तविक experiment बिना पीने/उपयोग के, केवल वयस्क की निगरानी में observe किया जा सकता है। कणों के नीचे बैठने का diagram बनाओ।"},
 {title:"🫗 निथारना (Decantation)",body:"जब भारी ठोस particles नीचे बैठ जाएँ, तो ऊपर के अपेक्षाकृत साफ द्रव को सावधानी से दूसरे बर्तन में उड़ेलकर अलग किया जा सकता है। इस प्रक्रिया को decantation कहा जाता है। यह sedimentation के बाद अधिक उपयोगी होती है।",remember:"Sedimentation → particles नीचे; Decantation → ऊपर का liquid धीरे-धीरे अलग।",visual:["🪨","💧","🫗"],visualText:["नीचे तलछट","ऊपर द्रव","निथारना"],think:"यदि पानी को जोर से हिलाकर तुरंत ऊपर से उड़ेलोगे, तो तलछट भी साथ क्यों जा सकती है?"},
 {title:"🧺 छनन / Filtration",body:"Filtration में filter की सहायता से कुछ ठोस particles को रोककर द्रव को आगे निकलने दिया जाता है। चाय से पत्तियाँ अलग करने के लिए छलनी/strainer का उपयोग इसका परिचित उदाहरण है।",remember:"Filter कुछ particles को रोकता है और liquid को passage देता है।",activity:"घर की चाय छानने की प्रक्रिया को ध्यान से देखकर components और filter की भूमिका बताओ।",visual:["🍵","🧺","💧"],visualText:["चाय","filter","तरल"],mistake:"Filter हर dissolved substance को नहीं रोकता; नमक-पानी को साधारण filter से अलग नहीं कर सकते।"},
 {title:"☀️ वाष्पीकरण (Evaporation)",body:"जब कोई ठोस पदार्थ द्रव में घुला हो, तो द्रव को हटाकर dissolved solid प्राप्त करने के लिए evaporation उपयोगी हो सकता है। नमक के घोल से नमक प्राप्त करना इसका परिचित उदाहरण है।",remember:"Dissolved solid + liquid → liquid हटाने के लिए evaporation उपयोगी हो सकती है।",visual:["🧂","💧","☀️"],visualText:["नमक","घोल","वाष्पीकरण"],think:"अगर नमक पानी में घुला है और filter से पानी छानते हैं, तो नमक क्यों नहीं रुकता?"},
 {title:"🔄 कौन-सी method कब?",body:"Method का चुनाव components की property पर निर्भर करता है। Visible large impurity → handpicking; light/heavy particles → winnowing; different particle size → sieving; insoluble heavy solid in liquid → sedimentation + decantation; solid particles from liquid → filtration; dissolved solid from solution → evaporation।",remember:"Method याद करने से पहले “किस property का अंतर है?” पूछो।",visual:["✋","💨","🕳️","🧺","☀️"],visualText:["छंटाई","फटकना","छलनी","filter","वाष्पीकरण"],activity:"6 imaginary mixtures के लिए सही method चुनो और हर choice का कारण एक line में लिखो।"},
 {title:"🧪 Combined methods",body:"कई mixtures में केवल एक method पर्याप्त नहीं होती। उदाहरण के लिए मिट्टी, पानी और छोटे dissolved पदार्थों वाले मिश्रण में पहले sedimentation/decantation या filtration से insoluble solid अलग किया जा सकता है, फिर परिस्थिति के अनुसार दूसरी प्रक्रिया की जरूरत पड़ सकती है।",remember:"Complex mixture → एक से अधिक separation steps संभव हैं।",think:"यदि पानी में मिट्टी भी है और नमक भी, तो केवल filtration करने से क्या मिलेगा और क्या नहीं मिलेगा?"},
 {title:"⚠️ Common mistakes & exam traps",body:"आम गलतियाँ: dissolved salt को filtration से अलग मानना; winnowing को केवल “हवा से कुछ भी अलग करना” समझना; sedimentation और decantation को एक ही step मानना; और method का नाम याद करके property भूल जाना। Exam में पहले mixture के components और उनके गुण पहचानो।",remember:"Property drives method. पहले components, फिर गुण, फिर separation method।",mistake:"Exam trap: नमक-पानी → evaporation; चाय-पत्ती → filtration; चावल-कंकड़ → handpicking; भूसी-अनाज → winnowing।"},
 {title:"🎯 परीक्षा में application",body:"Situation-based प्रश्न में three-step logic अपनाओ: (1) mixture क्या है? (2) components में कौन-सा useful difference है—size, weight, solubility या state? (3) कौन-सी method उस difference का उपयोग करती है? यह reasoning कई नए examples पर भी लागू हो सकती है।",remember:"Mixture → Property difference → Method",activity:"अपने लिए एक नया mixture बनाओ और बिना किताब देखे method का कारण समझाओ।"},
 {title:"🔁 Chapter Wrap-Up",body:"पृथक्करण का उद्देश्य mixture के components को उचित तरीके से अलग करना है। Handpicking visible impurities के लिए, winnowing light-heavy solids के लिए, sieving particle-size difference के लिए, sedimentation और decantation insoluble heavy solid-liquid mixtures के लिए, filtration solid particles को liquid से अलग करने के लिए और evaporation dissolved solids प्राप्त करने के लिए उपयोगी हो सकती है। कई बार steps को combine करना पड़ता है।",remember:"देखो → गुण पहचानो → method चुनो → सुरक्षित तरीके से अलग करो → परिणाम जाँचो।",think:"अब kitchen के किसी mixture को देखकर बताओ कि कौन-सा property difference तुम्हें separation method चुनने में मदद करेगा।"}
 ],
 challenge:[
 {question:"चावल में दिखाई दे रहे बड़े कंकड़ अलग करने के लिए कौन-सी method सबसे उपयुक्त है?",options:["Handpicking","Evaporation","Filtration","Condensation"],answer:0},
 {question:"अनाज और हल्की भूसी को अलग करने में कौन-सी method उपयोगी हो सकती है?",options:["Winnowing","Decantation","Filtration","Melting"],answer:0},
 {question:"Particle size में अंतर वाले सूखे solid mixture के लिए कौन-सी method उपयोगी है?",options:["Sieving","Evaporation","Decantation","Condensation"],answer:0},
 {question:"गंदे पानी में भारी मिट्टी के कण नीचे बैठने की प्रक्रिया क्या है?",options:["Sedimentation","Filtration","Winnowing","Evaporation"],answer:0},
 {question:"Sedimentation के बाद ऊपर का अपेक्षाकृत साफ पानी धीरे से अलग करने को क्या कहेंगे?",options:["Winnowing","Decantation","Sieving","Handpicking"],answer:1},
 {question:"चाय से पत्तियाँ अलग करने के लिए कौन-सी method सबसे उपयुक्त है?",options:["Filtration","Evaporation","Winnowing","Handpicking ही हमेशा"],answer:0},
 {question:"नमक के पानी से नमक प्राप्त करने के लिए कौन-सी प्रक्रिया उपयोगी हो सकती है?",options:["Evaporation","Filtration","Winnowing","Sieving"],answer:0},
 {question:"नमक-पानी को साधारण filter से अलग क्यों नहीं कर सकते?",options:["नमक dissolved है और filter से passage के रूप में जा सकता है","नमक बहुत भारी है","पानी solid है","filter पानी को रोकता ही नहीं"],answer:0},
 {question:"यदि mixture के दोनों solid components लगभग समान particle size के हों, तो sieving के बारे में क्या कहना उचित है?",options:["यह उपयुक्त नहीं हो सकती","यह हमेशा perfect होगी","यह evaporation बन जाएगी","यह condensation करेगी"],answer:0},
 {question:"सही reasoning कौन-सी है?",options:["Method का नाम याद करो, property भूल जाओ","Components पहचानो → property difference देखो → method चुनो","हर mixture के लिए filtration","हर solid mixture के लिए winnowing"],answer:1},
 {question:"यदि पानी में मिट्टी और नमक दोनों हों, तो केवल filtration के बाद क्या होगा?",options:["मिट्टी के particles हट सकते हैं, लेकिन dissolved salt पानी में रह सकता है","नमक पूरी तरह filter पर रुक जाएगा","दोनों तुरंत अलग हो जाएँगे","केवल पानी हटेगा"],answer:0},
 {question:"कई separation methods को क्रम से इस्तेमाल करने की जरूरत कब पड़ सकती है?",options:["जब mixture में अलग-अलग properties वाले कई components हों","कभी नहीं","केवल पानी के लिए","केवल grains के लिए"],answer:0}
 ]
};