window.chapter05={
  id:5,
  title:"लंबाई का मापन और गति",
  icon:"📏",
  goal:"अमानक और मानक इकाइयों, सही तरीके से लंबाई मापने, अनुमान लगाने, घुमावदार लंबाई मापने, स्थिति, विराम और विभिन्न प्रकार की गति को गतिविधियों तथा reasoning के साथ समझना।",
  sections:[
    {title:"🌟 हमें मापन की जरूरत क्यों पड़ती है?",body:"मान लो दो बच्चे कहते हैं कि मेज की लंबाई 12 कदम और 10 कदम है। क्या इसका मतलब मेज की लंबाई बदल गई? नहीं। उनके कदमों की लंबाई अलग हो सकती है। इसी कारण हमें ऐसी इकाइयों की जरूरत पड़ी जिनसे अलग-अलग लोग एक ही वस्तु के लिए लगभग समान माप प्राप्त कर सकें।",remember:"मापन किसी मात्रा को संख्या और इकाई के साथ व्यक्त करता है।",activity:"एक छोटी मेज को हाथ की span से मापो और फिर किसी दूसरे व्यक्ति की span से मापकर परिणामों की तुलना करो।",visual:["👣","✋","📏"],visualText:["कदम","हाथ की span","मानक माप"],think:"यदि हर व्यक्ति अपनी हथेली से सड़क की लंबाई मापे, तो क्या सभी के answers समान होंगे?"},
    {title:"🖐️ अमानक इकाइयाँ",body:"हाथ की span, कदम, उँगली की चौड़ाई या पैर जैसी शरीर-आधारित इकाइयाँ पुराने समय में उपयोगी रही हैं। वे स्थानीय तुलना में मदद कर सकती हैं, लेकिन अलग-अलग लोगों के शरीर के आकार अलग होने से परिणाम बदल सकते हैं।",remember:"अमानक इकाइयाँ सुविधाजनक हो सकती हैं, लेकिन उनकी तुलना सार्वभौमिक रूप से reliable नहीं होती।",activity:"अपने कदम से कमरे की लंबाई और परिवार के किसी सदस्य के कदम से वही लंबाई मापो। अंतर लिखो।"},
    {title:"📐 मानक इकाइयाँ",body:"मापन को अलग-अलग जगहों पर समझने और compare करने के लिए मानक इकाइयाँ विकसित हुईं। लंबाई के लिए meter, centimetre और millimetre जैसी इकाइयाँ उपयोग होती हैं। बड़ी दूरी के लिए kilometre उपयोगी है।",remember:"लंबाई की प्रमुख इकाइयाँ: km, m, cm, mm।",visual:["km","m","cm","mm"],visualText:["बड़ी दूरी","मानक लंबाई","छोटी लंबाई","बहुत छोटी लंबाई"],think:"सड़क की दो शहरों के बीच दूरी और पेंसिल की लंबाई के लिए एक ही unit चुनना सुविधाजनक क्यों नहीं होगा?"},
    {title:"🔢 संख्या + इकाई",body:"किसी माप को लिखते समय केवल संख्या पर्याप्त नहीं होती। “15” अधूरा है—15 cm, 15 m या 15 km अलग-अलग लंबाइयाँ बता सकते हैं। इसलिए संख्या और इकाई दोनों लिखना जरूरी है।",remember:"सही measurement = number + unit।",mistake:"Exam trap: “लंबाई 20 है” अधूरा है। “लंबाई 20 cm है” स्पष्ट measurement है।",visual:["20","cm","20 cm"],visualText:["केवल संख्या","केवल इकाई","सही माप"]},
    {title:"📏 सही scale कैसे रखें?",body:"स्केल या ruler को वस्तु की लंबाई के साथ सीधा और संपर्क में रखना चाहिए। वस्तु के एक सिरे को scale के zero mark से मिलाना सबसे आसान तरीका है। यदि zero mark उपलब्ध नहीं है, तो किसी दूसरे स्पष्ट mark से शुरुआत करके दोनों readings का अंतर लिया जा सकता है।",remember:"स्केल सीधा रखो और दोनों सिरों की readings का अंतर निकालो।",activity:"एक pencil को ruler से मापो। फिर ruler को थोड़ा तिरछा रखकर देखो कि placement measurement को कैसे प्रभावित कर सकता है।"},
    {title:"👁️ आँख की सही स्थिति",body:"स्केल पढ़ते समय आँख को उस निशान के ठीक सामने रखना चाहिए जहाँ measurement पढ़ना है। ऊपर या तिरछे से देखने पर reading में error आ सकता है। इसे parallax जैसी reading error की सरल शुरुआत के रूप में समझ सकते हैं।",remember:"Reading करते समय आँख और measurement mark लगभग एक ही level पर हों।",visual:["👁️","📏","✅"],visualText:["सही eye level","scale","बेहतर reading"],think:"यदि तुम ruler को दूर से तिरछे देखकर reading लो, तो सही value से अंतर क्यों आ सकता है?"},
    {title:"🪵 टूटा हुआ zero mark हो तो?",body:"अगर scale का zero वाला सिरा टूटा या घिसा हुआ है, तो measurement फिर भी किया जा सकता है। वस्तु के एक सिरे को किसी स्पष्ट mark—जैसे 1.0 cm—से मिलाओ और दूसरे सिरे की reading में से पहली reading घटाओ। उदाहरण: 1.0 cm से 10.4 cm तक का अंतर = 9.4 cm।",remember:"Broken zero में length = final reading − initial reading।",activity:"कागज पर 1 cm और 10 cm के बीच एक काल्पनिक वस्तु रखकर difference calculation करो।"},
    {title:"🧵 घुमावदार लंबाई कैसे मापें?",body:"सीधे ruler से curved line को ठीक-ठीक मापना कठिन हो सकता है। एक flexible thread को curve के साथ रखकर उसकी लंबाई mark की जा सकती है। फिर thread को सीधा करके ruler से उसकी लंबाई मापी जाती है।",remember:"Curved length → flexible thread → straight करके ruler से measurement।",visual:["〰️","🧵","📏"],visualText:["curve","thread","straight measure"],think:"गोल मेज की curved edge के लिए rigid 15 cm ruler को सीधे रखकर पूरी curve क्यों नहीं माप सकते?"},
    {title:"🎯 अनुमान और मापन",body:"मापन से पहले अनुमान लगाना useful skill है। यदि पेंसिल लगभग 15 cm की लगती है और वास्तविक measurement 14.8 cm आता है, तो अनुमान अच्छा था। अनुमान exact answer नहीं है; यह measurement की तैयारी और comparison में मदद करता है।",remember:"Estimate = सोच-समझकर लगाया गया लगभग मान; measurement = उपकरण से प्राप्त मान।",activity:"तीन वस्तुओं की लंबाई पहले अनुमान से लिखो, फिर ruler से मापो और error की तुलना करो।"},
    {title:"📍 वस्तु की स्थिति",body:"किसी वस्तु की position बताने के लिए एक reference point चुनना उपयोगी है। उदाहरण: “गेंद पेड़ से 3 m उत्तर की ओर है।” केवल दूरी ही नहीं, दिशा भी position को अधिक स्पष्ट बना सकती है।",remember:"Position को reference point, दूरी और आवश्यकता अनुसार दिशा से describe किया जा सकता है।",visual:["🌳","→","⚽"],visualText:["reference point","दिशा","object"],think:"“मैं स्कूल से 200 m दूर हूँ” की तुलना में “मैं स्कूल से 200 m पूर्व में हूँ” अधिक स्पष्ट क्यों है?"},
    {title:"🏃 गति और विराम",body:"यदि किसी वस्तु की position चुने गए reference point के सापेक्ष समय के साथ बदलती है, तो वस्तु को motion में कहा जा सकता है। यदि position में वह बदलाव नहीं होता, तो वस्तु rest में हो सकती है। Motion या rest का वर्णन reference point पर निर्भर कर सकता है।",remember:"Position changes with time → motion; position does not change relative to reference → rest।",activity:"किसी चलती साइकिल को एक fixed tree के reference से देखो। अब साइकिल पर बैठे व्यक्ति के reference से दूसरे object को सोचो।"},
    {title:"🔄 गति के अलग-अलग प्रकार",body:"वस्तुओं की गति अलग तरह की हो सकती है। सीधी दिशा में आगे बढ़ती ट्रेन का motion translatory/linear जैसा दिख सकता है। घूमता पंखा rotational motion करता है। झूला आगे-पीछे oscillatory motion कर सकता है। कुछ motions repeat होते हैं और कुछ नहीं।",remember:"सीधी/स्थान बदलती गति, घूमना और आगे-पीछे दोलन—इनके patterns पहचानो।",visual:["🚆","🌀","🎡","🪀"],visualText:["आगे बढ़ना","घूमना","घूर्णन","आगे-पीछे"],think:"क्या घड़ी की सुई और झूले की गति का pattern एक जैसा है? क्यों?"},
    {title:"⏱️ आवर्ती और अनावर्ती गति",body:"जो motion लगभग समान समय के बाद दोहराता है, उसे periodic motion के रूप में पहचाना जा सकता है। झूले या कुछ घूर्णन motions में repetition दिखाई दे सकती है। हर motion periodic नहीं होता—सड़क पर चलती कार का रास्ता और समय हमेशा समान pattern में repeat नहीं होता।",remember:"Periodic motion में pattern समय-समय पर दोहराता है।",think:"सूर्योदय-सूर्यास्त का दैनिक cycle repeat होता है; क्या यह periodic pattern का एक प्राकृतिक उदाहरण है?"},
    {title:"🧠 Chapter Wrap-Up",body:"मापन हमें किसी वस्तु की लंबाई को number और unit में व्यक्त करने देता है। अमानक units की सीमाएँ समझने के बाद standard units उपयोगी बनते हैं। सही scale placement, eye level और broken zero की स्थिति measurement accuracy को प्रभावित करती है। Curved length के लिए flexible thread उपयोगी हो सकता है। Position को reference point से describe किया जाता है और position के समय के साथ बदलने से motion समझी जाती है। अलग motions के patterns पहचानना scientific observation को मजबूत बनाता है।",remember:"Measure well → Estimate → Use standard unit → Read correctly → Describe position → Identify motion",think:"अब किसी एक रोज़मर्रा की वस्तु को चुनकर बताओ: उसकी लंबाई कैसे मापोगे, कौन-सी unit चुनोगे और उसकी motion कैसे describe करोगे?"}
  ],
  challenge:[
    {question:"किसी मेज की लंबाई अलग-अलग विद्यार्थियों के handspan से अलग क्यों मिल सकती है?",options:["मेज बदलती रहती है","हर विद्यार्थी की handspan की लंबाई अलग हो सकती है","मापन हमेशा गलत है","मेज का रंग बदलता है"],answer:1},
    {question:"कौन-सा measurement पूरा और स्पष्ट है?",options:["12","12 long","12 cm","cm"],answer:2},
    {question:"Zero mark टूटे होने पर 2.0 cm से 14.5 cm तक वस्तु का माप क्या होगा?",options:["16.5 cm","12.5 cm","14.5 cm","2.0 cm"],answer:1},
    {question:"Curved line की लंबाई मापने के लिए सबसे उपयुक्त तरीका कौन-सा है?",options:["सीधे ruler को curve पर अनुमान से रखें","thread से curve follow करके thread को सीधा कर ruler से मापें","केवल रंग देखकर बताएं","वस्तु को छोटा करें"],answer:1},
    {question:"Ruler पढ़ते समय आँख बहुत तिरछी स्थिति में होने पर क्या समस्या हो सकती है?",options:["वस्तु की लंबाई बदल जाती है","reading error हो सकता है","unit बदल जाती है","ruler magnetic हो जाता है"],answer:1},
    {question:"कौन-सा अनुमान measurement से पहले useful हो सकता है?",options:["पेंसिल लगभग 15 cm की है","पेंसिल निश्चित रूप से 15.000 cm है","पेंसिल नहीं मापी जा सकती","पेंसिल की कोई length नहीं"],answer:0},
    {question:"Position को अधिक स्पष्ट बताने के लिए किसकी जरूरत पड़ सकती है?",options:["reference point और दूरी/दिशा","केवल रंग","केवल आकार","केवल वस्तु का नाम"],answer:0},
    {question:"यदि गेंद पेड़ से दूर जाती जा रही है, तो पेड़ को reference point मानने पर क्या बदल रहा है?",options:["गेंद का रंग","गेंद की position","पेड़ का आकार","गेंद का नाम"],answer:1},
    {question:"घूमते पंखे की गति किस प्रकार की है?",options:["rotational","केवल linear","केवल rest","कोई motion नहीं"],answer:0},
    {question:"झूले का आगे-पीछे जाना किस type of motion का उदाहरण है?",options:["oscillatory","केवल translatory","केवल rotational","निष्क्रिय"],answer:0},
    {question:"Periodic motion की प्रमुख विशेषता क्या है?",options:["यह कभी दोहरता नहीं","यह समय के बाद pattern को दोहराता है","यह हमेशा सीधा चलता है","इसमें समय नहीं लगता"],answer:1},
    {question:"वैज्ञानिक मापन का सबसे अच्छा क्रम कौन-सा है?",options:["अनुमान → उचित उपकरण → सही placement → reading → unit लिखना","केवल अनुमान","reading → unit हटाना → निष्कर्ष","ruler तोड़ना → measurement"],answer:0}
  ]
};