window.chapter07={
 id:7,title:"तापमान और उसका मापन",icon:"🌡️",
 goal:"गर्म-ठंडा होने के अनुभव और तापमान में अंतर, तापमान मापने की आवश्यकता, विभिन्न थर्मामीटर, Celsius scale, सही reading, प्रयोगात्मक अवलोकन और रोज़मर्रा के applications को समझना।",
 sections:[
 {title:"🌟 गरम और ठंडा—पर केवल महसूस करना काफी है?",body:"हम अपने हाथ से किसी वस्तु को गर्म या ठंडा महसूस कर सकते हैं, लेकिन यह सटीक तापमान नहीं बताता। एक ही वस्तु अलग परिस्थितियों में अलग महसूस हो सकती है। वैज्ञानिक तुलना के लिए हमें तापमान को किसी उपकरण से मापना पड़ता है।",remember:"Feeling gives an impression; thermometer gives a measurement।",visual:["✋","🌡️","📊"],visualText:["महसूस","मापो","तुलना करो"],think:"एक हाथ को ठंडे पानी और दूसरे को गुनगुने पानी में थोड़ी देर रखने के बाद दोनों हाथों को एक ही गुनगुने पानी में डालो। दोनों hands का अनुभव एक जैसा होगा? इससे हमें क्या सीख मिलती है?"},
 {title:"🌡️ तापमान क्या है?",body:"तापमान किसी वस्तु की गर्माहट या ठंडक की माप से जुड़ी भौतिक राशि है। जब हम कहते हैं कि एक वस्तु दूसरी से अधिक गर्म है, तो हम सामान्यतः उसके तापमान की तुलना कर रहे होते हैं। तापमान को एक संख्या और unit के साथ दर्ज किया जा सकता है।",remember:"तापमान को मापकर संख्या में व्यक्त किया जा सकता है।",activity:"अलग-अलग स्थानों—जैसे कमरा और बाहर—का तापमान यदि उपकरण से उपलब्ध हो तो note करके तुलना करो।"},
 {title:"🧪 थर्मामीटर क्यों इस्तेमाल करते हैं?",body:"थर्मामीटर तापमान मापने का उपकरण है। इसका उपयोग केवल “गर्म” या “ठंडा” कहने से बेहतर है क्योंकि यह एक scale पर संख्यात्मक reading देता है। अलग उद्देश्यों के लिए अलग प्रकार के थर्मामीटर बनाए जाते हैं।",remember:"थर्मामीटर का काम temperature को measurable reading में बदलना है।",visual:["🌡️","🔢","°C"],visualText:["उपकरण","संख्या","unit"],think:"यदि दो दिनों को केवल “आज ज्यादा गर्म है” कहकर compare करें, तो exact difference क्यों नहीं बता पाएँगे?"},
 {title:"🩺 शरीर का तापमान और clinical thermometer",body:"मानव शरीर का तापमान मापने के लिए clinical thermometer का उपयोग किया जाता है। इसे उपयोग करने की सही प्रक्रिया और hygiene का ध्यान रखना जरूरी है। Modern digital thermometers reading को screen पर दिखा सकते हैं।",remember:"शरीर का तापमान मापने वाले उपकरण का उपयोग उसके निर्देश के अनुसार करना चाहिए।",activity:"किसी thermometer को बिना अनुमति और बिना सही निर्देश के न इस्तेमाल करो। यदि घर में कोई सुरक्षित thermometer हो तो किसी वयस्क से उसकी सही reading प्रक्रिया समझो।",mistake:"गलती: हर thermometer को शरीर पर एक ही तरीके से इस्तेमाल किया जा सकता है—यह जरूरी नहीं।"},
 {title:"🌡️ Laboratory thermometer की सोच",body:"Laboratory thermometer का उपयोग प्रयोगशाला में पदार्थों या liquids का तापमान मापने के लिए किया जाता है। इसका उपयोग उस काम और range के अनुसार किया जाता है जिसके लिए वह बनाया गया है।",remember:"Thermometer चुनते समय उसके purpose और measurement range को देखो।",think:"क्या ऐसा thermometer जो किसी विशेष काम के लिए बनाया गया है, हर दूसरे काम में सुरक्षित और accurate होगा? क्यों?"},
 {title:"🔢 Celsius scale पढ़ना",body:"तापमान की एक सामान्य इकाई degree Celsius (°C) है। Scale पर divisions को ध्यान से पढ़ना चाहिए। Reading लेते समय यह देखो कि liquid column या digital display किस value को दिखा रहा है।",remember:"संख्या पढ़ने के साथ °C जैसी unit लिखना मत भूलो।",visual:["0°C","25°C","50°C"],visualText:["scale point","scale point","scale point"],activity:"कागज पर एक thermometer scale बनाओ और अलग-अलग readings mark करो—जैसे 10°C, 25°C और 40°C।"},
 {title:"👁️ सही reading कैसे लें?",body:"Thermometer की reading गलत होने के कई कारण हो सकते हैं—गलत position, scale को गलत पढ़ना या measurement के दौरान उचित स्थिरता न रखना। Analog liquid thermometer में reading लेने से पहले liquid column को स्थिर होने देना और eye level ठीक रखना महत्वपूर्ण हो सकता है।",remember:"उपकरण सही रखो → reading स्थिर होने दो → scale सही angle से पढ़ो।",mistake:"Exam trap: thermometer को बहुत तिरछे देखकर reading लेना measurement error पैदा कर सकता है।",think:"यदि liquid column अभी ऊपर-नीचे हो रहा हो और तुम तुरंत number लिख दो, तो reading unreliable क्यों हो सकती है?"},
 {title:"📈 तापमान में बदलाव दर्ज करना",body:"यदि किसी वस्तु का तापमान समय के साथ बदल रहा है, तो हम अलग-अलग समय पर readings लेकर table बना सकते हैं। फिर इन values को graph में रखकर बदलाव का pattern देखा जा सकता है।",remember:"Repeated measurements से change का pattern ज्यादा स्पष्ट हो सकता है।",activity:"एक काल्पनिक उदाहरण बनाओ: 0 min = 20°C, 5 min = 24°C, 10 min = 28°C. बताओ कि तापमान किस दिशा में बदल रहा है।",visual:["20°C","24°C","28°C"],visualText:["0 min","5 min","10 min"]},
 {title:"🔥 रोज़मर्रा में तापमान",body:"तापमान मौसम, खाना पकाने, शरीर की देखभाल और कई तकनीकी कामों में महत्वपूर्ण है। लेकिन हर जगह एक ही thermometer उपयोग नहीं होता। सही measurement के लिए purpose के अनुसार tool चुनना जरूरी है।",remember:"Context बदले तो सही measurement tool भी बदल सकता है।",think:"मौसम का तापमान मापने और शरीर का तापमान मापने के लिए एक ही उपकरण चुनना हमेशा उचित क्यों नहीं होगा?"},
 {title:"🧠 अनुभव बनाम प्रमाण",body:"विज्ञान में sensory experience useful starting point हो सकता है, लेकिन precise comparison के लिए measurable evidence ज्यादा भरोसेमंद होता है। यह chapter Chapter 1 की scientific thinking से जुड़ता है: अनुमान बनाओ, फिर मापकर जाँच करो।",remember:"अनुभव → अनुमान; मापन → प्रमाण।",activity:"दो वस्तुओं के बारे में पहले अपनी prediction लिखो और फिर thermometer reading से compare करने की कल्पना करो।"},
 {title:"⚠️ Common Mistakes और Exam Traps",body:"आम गलतियाँ: temperature को heat के समान मान लेना, unit भूल जाना, किसी भी thermometer को हर काम के लिए suitable समझना, और गलत angle पर reading लेना। Question में purpose और measurement situation को ध्यान से पढ़ो।",remember:"Temperature measurement में instrument, scale, unit और reading method—चारों पर ध्यान दो।",mistake:"“गरम महसूस हुआ इसलिए temperature बहुत ज्यादा है”—यह exact scientific measurement नहीं है।"},
 {title:"🎯 परीक्षा में application",body:"Exam question में पहले पहचानो कि क्या मापना है, किस tool की जरूरत है, scale क्या है और reading कैसे interpret करनी है। Situation-based questions में सही instrument चुनना और unit लिखना अक्सर marks बचाता है।",remember:"Question → purpose → instrument → scale/unit → reading → conclusion",activity:"तीन situations बनाओ: body temperature, liquid in experiment, outdoor air. हर situation के लिए उपयुक्त type का thermometer सोचो।"},
 {title:"🔁 Chapter Wrap-Up",body:"हमारे हाथ गर्म-ठंडा होने का अनुभव देते हैं, लेकिन exact comparison के लिए temperature मापना जरूरी है। Thermometer इस काम का उपकरण है। Celsius एक सामान्य temperature scale है। सही instrument, सही placement, stable reading, eye position और unit का ध्यान measurement की accuracy बढ़ाते हैं। अलग कामों के लिए अलग thermometers का उपयोग हो सकता है।",remember:"Feel → Question → Choose thermometer → Measure → Read scale → Record unit → Compare",think:"अब किसी temperature measurement को देखते ही अपने आप ये छह सवाल पूछो: क्या माप रहे हैं, किससे, किस unit में, कहाँ से reading ले रहे हैं, कितना reliable है, और इसका क्या अर्थ है?"}
 ],
 challenge:[
 {question:"हाथ से किसी वस्तु का तापमान महसूस करने की तुलना में thermometer का मुख्य लाभ क्या है?",options:["वह रंग बदलता है","वह संख्यात्मक measurement देता है","वह वस्तु का आकार बदलता है","वह हमेशा ठंडा करता है"],answer:1},
 {question:"तापमान की एक सामान्य unit कौन-सी है?",options:["मीटर","डिग्री Celsius","किलोग्राम","लीटर"],answer:1},
 {question:"किसी thermometer को हर प्रकार के काम में इस्तेमाल करना क्यों उचित नहीं है?",options:["हर thermometer का purpose और range अलग हो सकता है","thermometer का कोई scale नहीं","temperature की कोई unit नहीं","सभी thermometers समान हैं"],answer:0},
 {question:"Analog thermometer की reading में eye level गलत होने पर क्या हो सकता है?",options:["वस्तु का temperature बदल जाता है","reading error हो सकता है","unit बदल जाती है","thermometer गायब हो जाता है"],answer:1},
 {question:"यदि किसी liquid का तापमान 20°C से 28°C हो जाए, तो क्या कहा जा सकता है?",options:["तापमान घटा","तापमान बढ़ा","तापमान समान रहा","कोई जानकारी नहीं"],answer:1},
 {question:"0 min = 20°C, 5 min = 24°C, 10 min = 28°C. कौन-सा pattern दिखता है?",options:["लगातार वृद्धि","लगातार कमी","कोई बदलाव नहीं","पहले घटा फिर बढ़ा"],answer:0},
 {question:"कौन-सा कथन सबसे वैज्ञानिक है?",options:["यह गरम लग रहा है, इसलिए इसका तापमान निश्चित 50°C है","इसे thermometer से मापकर reading दर्ज करें","दोस्त ने कहा यह गर्म है","रंग देखकर temperature बताओ"],answer:1},
 {question:"यदि thermometer की reading स्थिर होने से पहले value लिख दी जाए, तो समस्या क्या है?",options:["reading unreliable हो सकती है","unit गायब हो जाती है","temperature हमेशा zero हो जाता है","thermometer magnet बन जाता है"],answer:0},
 {question:"शरीर का तापमान मापने के लिए purpose-specific thermometer चुनने का मुख्य कारण क्या है?",options:["सही उपयोग और उपयुक्त measurement के लिए","केवल रंग के लिए","केवल सजावट के लिए","क्योंकि सभी thermometers एक जैसे हैं"],answer:0},
 {question:"किस विकल्प में measurement पूरा है?",options:["25","25 गर्म","25°C","degree"],answer:2},
 {question:"Chapter 1 की वैज्ञानिक सोच और temperature measurement में कौन-सा संबंध है?",options:["अनुमान को बिना जाँच सही मानना","question → measure → evidence → conclusion","data छिपाना","केवल याद करना"],answer:1},
 {question:"दो दिनों की exact temperature comparison के लिए कौन-सा तरीका बेहतर है?",options:["केवल feel करना","दोनों के temperature को समान unit में मापना","केवल मौसम देखकर बताना","दोस्त का अनुमान लेना"],answer:1}
 ]
};