window.mathsChapter02={
 id:2,title:'अंकगणितीय व्यंजक',icon:'🧮',
 goal:'संख्याओं और गणितीय संक्रियाओं से बने व्यंजकों को समझना, brackets और operations के सही क्रम से step-by-step हल करना, तथा अपने उत्तर को जाँचना।',
 sections:[
 {title:'🌟 व्यंजक क्या होता है?',body:'संख्याओं और गणितीय संक्रियाओं से बनी गणितीय रचना को व्यंजक (expression) कह सकते हैं। जैसे 7 + 5, 18 − 3, 6 × 4 और 24 ÷ 6। व्यंजक में बराबर (=) का चिह्न जरूरी नहीं होता; = लगाने पर हम दो राशियों के बीच equality का कथन बना रहे होते हैं।',remember:'Expression को equation से अलग पहचानो: 7 + 5 एक expression है, जबकि 7 + 5 = 12 एक equation है।',visual:['7 + 5','18 − 3','6 × 4'],visualText:['जोड़','घटाव','गुणा'],think:'क्या “20” अकेले भी एक expression माना जा सकता है? अपने कारण पर विचार करो।'},
 {title:'➕➖✖️➗ चार मूल संक्रियाएँ',body:'अंकगणितीय व्यंजकों में जोड़, घटाव, गुणा और भाग जैसी संक्रियाएँ होती हैं। किसी expression को हल करते समय केवल बाएँ से दाएँ भागना हमेशा सही नहीं होता, क्योंकि multiplication और division की priority addition और subtraction से अलग होती है।',remember:'हर symbol को पहचानो और फिर operation की priority देखो।',activity:'इन चार चिन्हों के लिए अपने जीवन से एक-एक उदाहरण सोचो: +, −, ×, ÷।'},
 {title:'🧩 एक से अधिक operations वाला expression',body:'मान लो expression है 8 + 3 × 4। यदि हम पहले जोड़ें तो 11 × 4 = 44 मिलेगा, लेकिन सही convention के अनुसार multiplication पहले होगा: 3 × 4 = 12, फिर 8 + 12 = 20। इसलिए operations का क्रम बहुत महत्वपूर्ण है।',remember:'Priority बदले बिना calculation शुरू मत करो।',think:'8 + 3 × 4 में 20 और 44 में से कौन-सा answer सही है और क्यों?'},
 {title:'📋 Operations का क्रम',body:'सामान्यतः पहले brackets के अंदर की calculation की जाती है। उसके बाद multiplication और division, और अंत में addition और subtraction किए जाते हैं। समान priority वाले multiplication/division या addition/subtraction होने पर उन्हें बाएँ से दाएँ पढ़ना सुरक्षित नियम है।',remember:'Bracket → Multiplication/Division → Addition/Subtraction।',visual:['( )','× ÷','+ −'],visualText:['पहले','फिर','अंत में'],mistake:'गलती: हर expression को केवल left-to-right हल करना।'},
 {title:'( ) Brackets का काम',body:'Brackets expression के किसी हिस्से को पहले करने का संकेत देते हैं। उदाहरण: 6 × (3 + 2) में पहले 3 + 2 = 5, फिर 6 × 5 = 30। यदि bracket हटा दें तो 6 × 3 + 2 = 20 हो सकता है। इसलिए bracket केवल decoration नहीं है; वह meaning बदल सकता है।',remember:'Bracket expression की priority को नियंत्रित करता है।',think:'4 × (10 − 3) और 4 × 10 − 3 में अंतर क्यों आता है?'},
 {title:'🔁 Step-by-step calculation',body:'एक कठिन expression को एक ही line में हल करने की जगह intermediate steps लिखना बेहतर है। उदाहरण: 36 ÷ 6 + 4 × 2 → 6 + 8 → 14। हर step में एक स्पष्ट operation पूरा करने से calculation error कम होता है।',remember:'एक step = एक साफ बदलाव।',activity:'किसी expression को 2–3 lines में solve करके हर line के बीच arrow लगाओ।'},
 {title:'✅ उत्तर की जाँच कैसे करें?',body:'Answer check करने के लिए उलटी सोच (reverse operation), estimation या दूसरी method उपयोग की जा सकती है। जैसे 48 ÷ 6 = 8 को check करने के लिए 8 × 6 = 48 देख सकते हैं। Addition को subtraction से भी check किया जा सकता है।',remember:'Solve के बाद Verify भी करो।',think:'यदि 72 ÷ 9 = 7 लिख दिया गया, तो बिना दोबारा division किए mistake जल्दी कैसे पकड़ोगे?'},
 {title:'🧠 Estimate से गलती पकड़ो',body:'Exact calculation से पहले approximate size का अंदाजा useful हो सकता है। उदाहरण: 398 + 205 लगभग 400 + 200 = 600 के पास होना चाहिए। इसलिए यदि exact answer 1,200 आया, तो हमें calculation फिर check करनी चाहिए।',remember:'Estimate answer का rough range बताता है; exact answer का replacement नहीं है।',activity:'527 + 286 का पहले अनुमान लगाओ, फिर exact answer निकालो और compare करो।'},
 {title:'⚠️ Common mistakes',body:'बार-बार दिखने वाली गलतियाँ: bracket को ignore करना, multiplication से पहले addition करना, division को गलत order में करना, sign copy न करना, और intermediate steps न लिखना। बड़े expression में छोटे steps अधिक reliable होते हैं।',remember:'Priority + signs + steps = accurate calculation।',mistake:'Exam trap: 24 ÷ 3 × 2 को बिना सोचे 24 ÷ 6 मत बनाओ। ÷ और × समान priority के हैं, इसलिए left-to-right: 24 ÷ 3 = 8, फिर 8 × 2 = 16।'},
 {title:'🎯 परीक्षा में expression questions',body:'Exam में पहले brackets पहचानो, फिर ×/÷ और अंत में +/− देखो। यदि options दिए हों तो impossible estimates हटाओ। Working दिखाना विशेषकर harder questions में अपनी reasoning को check करने में मदद करता है।',remember:'Question पढ़ो → priority mark करो → stepwise solve → estimate/check।',activity:'एक कठिन expression चुनो और हर operation पर छोटा tick लगाकर solve करो।'},
 {title:'🔥 Challenge strategy',body:'जब expression लंबा हो, पूरा answer मन में करने की कोशिश मत करो। पहले structure लिखो। उदाहरण: 50 − 4 × (6 + 2) → bracket = 8 → multiplication = 32 → subtraction = 18। इस तरह हर intermediate value अगले step को आसान बनाती है।',remember:'Complex expression = छोटे verified steps।',think:'क्या 50 − 4 × (6 + 2) में 18 के बजाय 368 आ सकता है? नहीं तो क्यों?'},
 {title:'🔁 Chapter Wrap-Up',body:'अंकगणितीय व्यंजक संख्याओं और operations से बनते हैं। उनके अर्थ को सही निकालने के लिए brackets और operations की priority समझना जरूरी है। सामान्य क्रम है brackets, फिर multiplication/division, फिर addition/subtraction; समान priority वाले operations को left-to-right किया जाता है। Stepwise work, estimation और reverse-operation checks calculation को reliable बनाते हैं।',remember:'Bracket → × ÷ → + − → Check।',think:'अपने शब्दों में समझाओ: “operation का क्रम” गलत होने पर एक ही numbers का answer क्यों बदल सकता है?'}
 ],
 challenge:[
 {question:'7 + 5 × 2 का सही मान क्या है?',options:['24','17','19','14'],answer:1,explanation:'पहले 5 × 2 = 10, फिर 7 + 10 = 17।',example:'जैसे 5 पैकेट में 2-2 वस्तुएँ और 7 अलग वस्तुएँ हों, कुल 17 होंगी।'},
 {question:'6 × (3 + 2) का सही उत्तर क्या है?',options:['20','30','18','11'],answer:1,explanation:'Bracket पहले: 3 + 2 = 5; फिर 6 × 5 = 30।',example:'यदि 6 groups में हर group में 3 लाल और 2 नीली वस्तुएँ हों, तो कुल 30 वस्तुएँ होंगी।'},
 {question:'24 ÷ 3 × 2 को सही क्रम में करने पर उत्तर क्या होगा?',options:['4','8','16','12'],answer:2,explanation:'÷ और × समान priority के हैं, इसलिए left-to-right: 24 ÷ 3 = 8, फिर 8 × 2 = 16।',example:'24 चीज़ों को 3 बराबर groups में बाँटो, फिर groups की संख्या को 2 से गुणा करो: 16।'},
 {question:'18 − 4 × 3 में पहले कौन-सा operation होगा?',options:['18 − 4','4 × 3','18 − 3','सभी साथ'],answer:1,explanation:'Multiplication addition/subtraction से पहले होती है।',example:'4 × 3 को पहले पूरा करके 18 − 12 = 6 मिलेगा।'},
 {question:'36 ÷ 6 + 4 × 2 का मान क्या है?',options:['20','14','16','10'],answer:1,explanation:'36 ÷ 6 = 6 और 4 × 2 = 8; फिर 6 + 8 = 14।',example:'दो अलग calculations पहले पूरी करके फिर उनका योग किया गया।'},
 {question:'किस expression में bracket सबसे पहले priority देगा?',options:['8 + 2 × 3','5 × (4 + 1)','12 ÷ 3 + 2','9 − 2 × 2'],answer:1,explanation:'(4 + 1) bracket के अंदर है, इसलिए पहले वही solve होगा।',example:'6 × (3 + 2) में group के अंदर की संख्या पहले तय होती है।'},
 {question:'48 ÷ 6 = 8 को check करने का अच्छा तरीका क्या है?',options:['8 + 6','8 × 6','8 − 6','48 + 8'],answer:1,explanation:'Division को multiplication से reverse-check किया जा सकता है: 8 × 6 = 48।',example:'48 chocolates को 6 groups में बाँटकर 8 per group मिले, तो 8 groups of 6 वापस 48 होंगे।'},
 {question:'398 + 205 का अच्छा estimate कौन-सा है?',options:['लगभग 200','लगभग 400','लगभग 600','लगभग 1000'],answer:2,explanation:'398 लगभग 400 और 205 लगभग 200, इसलिए total लगभग 600।',example:'Shopping में ₹398 और ₹205 खर्च हों तो rough total ₹600 के आसपास होगा।'},
 {question:'50 − 4 × (6 + 2) का उत्तर क्या है?',options:['18','38','368','14'],answer:0,explanation:'Bracket: 6 + 2 = 8; multiplication: 4 × 8 = 32; subtraction: 50 − 32 = 18।',example:'50 points में से 4 groups के 8-8 points हटाने पर 18 बचते हैं।'},
 {question:'कौन-सा कथन सही है?',options:['हर expression left-to-right solve होता है','Bracket को ignore किया जा सकता है','पहले bracket, फिर ×/÷, फिर +/−','Addition हमेशा सबसे पहले होती है'],answer:2,explanation:'Priority order structure को follow करना जरूरी है।',example:'6 × (3 + 2) में bracket ignore करने से answer बदल जाता है।'},
 {question:'यदि 72 ÷ 9 = 7 लिखा गया है, सबसे तेज़ check क्या हो सकता है?',options:['7 × 9 = 63, इसलिए answer गलत है','7 + 9 = 16','72 − 7','72 × 9'],answer:0,explanation:'यदि quotient 7 होता तो 7 × 9 = 63 होना चाहिए, 72 नहीं।',example:'Division check करने के लिए quotient × divisor देखो।'},
 {question:'एक student ने 8 + 3 × 4 = 44 किया। गलती कहाँ हुई?',options:['3 × 4 नहीं करना चाहिए था','उसने addition को multiplication से पहले कर दिया','8 गलत number है','4 को divide करना चाहिए था'],answer:1,explanation:'सही order में 3 × 4 = 12, फिर 8 + 12 = 20।',example:'Priority बदलने से operation की meaning और final result दोनों बदल जाते हैं।'},
 {question:'कौन-सा workflow सबसे reliable है?',options:['Guess → answer','Priority पहचानो → stepwise solve → check','बस calculator-style one line','पहले addition हमेशा'],answer:1,explanation:'Structure पहचानकर छोटे verified steps और final check errors कम करते हैं।',example:'लंबे expression को छोटे blocks में solve करना puzzle को आसान बनाता है।'},
 {question:'18 + 24 ÷ 6 × 2 का सही उत्तर क्या है?',options:['14','26','24','42'],answer:1,explanation:'24 ÷ 6 = 4, फिर 4 × 2 = 8, फिर 18 + 8 = 26।',example:'Division और multiplication को left-to-right करके फिर addition करें।'},
 {question:'कौन-सा expression 20 देगा?',options:['8 + 3 × 4','(8 + 3) × 4','20 − 4 × 3','40 ÷ 2 + 1'],answer:0,explanation:'8 + 3 × 4 = 8 + 12 = 20।',example:'पहले multiplication, फिर addition।'}
 ]
};