window.mathsChapter04={id:4,title:'अक्षर-संख्याओं वाले व्यंजक',icon:'🔤',goal:'अक्षरों को संख्याओं के साथ प्रयोग करके व्यंजक बनाना, मान निकालना, patterns पहचानना और step-by-step reasoning विकसित करना।',sections:[
{title:'🔤 अक्षर गणित में क्यों आते हैं?',body:'कभी-कभी हमें किसी संख्या का निश्चित मान नहीं पता होता या वह बदल सकती है। ऐसे में हम उस संख्या को किसी अक्षर, जैसे x, y या n, से दर्शा सकते हैं। यह अक्षर एक variable की तरह काम करता है।',remember:'अक्षर किसी अज्ञात या बदलने वाली संख्या को दर्शा सकता है।',example:'यदि एक पेंसिल की कीमत ₹10 है और पेंसिलों की संख्या n है, तो कुल कीमत 10n होगी।',think:'यदि n बदल जाए तो 10n कैसे बदलेगा?'
},{title:'🧩 Variable और Constant',body:'Variable वह quantity है जिसका मान बदल सकता है। Constant का मान निश्चित रहता है। उदाहरण: 5n में n variable है और 5 constant है।',remember:'Variable बदल सकता है; constant निश्चित रहता है।',activity:'अलग-अलग expressions में variable और constant को पहचानो।'
},{title:'✍️ Expression कैसे बनाते हैं?',body:'“किसी संख्या में 7 जोड़ो” को n + 7 लिखा जा सकता है। “किसी संख्या का 3 गुना” को 3n लिखा जा सकता है। भाषा को mathematical expression में बदलना एक महत्वपूर्ण skill है।',remember:'शब्दों को operations में बदलो: जोड़ = +, घटाना = −, गुणा = ×, भाग = ÷।',example:'किसी संख्या x का 4 गुना और उसमें 3 जोड़ना → 4x + 3।'
},{title:'🧮 गुणांक (Coefficient)',body:'Expression 7x में 7, x का coefficient है। यह बताता है कि x कितनी बार लिया गया है। 1x को सामान्यतः x ही लिखते हैं।',remember:'7x में 7 coefficient है और x variable।',think:'3x और x में क्या अंतर है?'
},{title:'🎯 किसी variable का मान रखकर expression हल करना',body:'यदि x = 5 हो, तो 3x + 2 में x की जगह 5 रखो: 3(5)+2 = 15+2 = 17। इसे substitution कहते हैं।',remember:'पहले value substitute करो, फिर operations को सही क्रम में करो।',example:'यदि n=4, तो 2n+6 = 8+6 = 14।'
},{title:'🪜 Step-by-step substitution',body:'एक safe method है: Step 1 value लिखो → Step 2 brackets रखो → Step 3 multiplication/division → Step 4 addition/subtraction → Step 5 answer check।',remember:'एक ही step में बहुत कुछ मत करो; हर step साफ लिखो।',mistake:'गलती: 2x को x+2 समझ लेना। 2x का मतलब 2 × x है।'
},{title:'🔄 Same expression, different values',body:'एक ही expression अलग values पर अलग answers दे सकता है। जैसे x+4 में x=2 पर 6 और x=10 पर 14 मिलेगा। Expression rule वही रहता है; input बदलता है।',remember:'Rule स्थिर हो सकता है, लेकिन variable की value बदलने से result बदलता है।'
},{title:'📈 Pattern को expression में बदलना',body:'Patterns में हर step के साथ क्या बदल रहा है, यह खोजकर expression बनाया जा सकता है। यदि हर अगली संख्या 3 बढ़ रही है, तो term number n के साथ 3n जैसे rules मिल सकते हैं; pattern को कई terms से verify करना जरूरी है।',remember:'Pattern rule को कम-से-कम 2–3 terms पर जाँचो।',think:'2, 5, 8, 11,… में nवें term के लिए कौन-सा rule संभव है?'
},{title:'💰 Real-life expressions',body:'अगर notebook की कीमत ₹40 और pens की कीमत ₹10 है, तथा notebooks की संख्या n है, तो कुल कीमत 40n + 10p लिखी जा सकती है, जहाँ p pens की संख्या है।',remember:'Real situation को variables और operations में translate करना expression skill है।',example:'3 notebooks और 2 pens: 40(3)+10(2)=140।'
},{title:'🧠 Like terms की शुरुआती समझ',body:'2x और 5x में variable वही x है, इसलिए उन्हें जोड़कर 7x किया जा सकता है। लेकिन 2x और 5y अलग variables हैं, इसलिए उन्हें 7x या 7y नहीं बनाया जा सकता।',remember:'Same variable वाले terms को जोड़ते समय coefficients जोड़ते हैं।',mistake:'2x + 3 को 5x नहीं बनाना चाहिए, क्योंकि एक term में x है और दूसरे में नहीं।'
},{title:'⚖️ Expression और equation का अंतर',body:'Expression में बराबर का चिन्ह जरूरी नहीं होता, जैसे 3x+2। Equation में equality होती है, जैसे 3x+2=11।',remember:'Expression = mathematical phrase; Equation = two expressions made equal।'
},{title:'🔍 Answer check कैसे करें?',body:'Substitution के बाद result को reverse-thinking से check करो। उदाहरण: 3x+2, x=5 → 17। अब 3×5+2 फिर से करके 17 मिलता है तो calculation consistent है।',remember:'Check करना खासकर multi-step questions में जरूरी है।',activity:'एक expression चुनकर दो अलग methods से check करो।'
},{title:'⚠️ Common exam traps',body:'मुख्य traps: coefficient और variable उलट देना; 4x को 4+x पढ़ना; negative sign भूलना; bracket के बाहर multiplication लागू न करना; value substitute करने के बाद गलत operation order अपनाना।',remember:'Symbol को उसके mathematical meaning के साथ पढ़ो।',mistake:'−2x में negative sign भी coefficient का हिस्सा है; इसे +2x मत समझो।'
},{title:'🎯 Hard application thinking',body:'किसी rectangle की लंबाई x cm और चौड़ाई 3 cm है। उसकी perimeter 2(x+3) होगी। यहाँ expression केवल calculation नहीं, situation का mathematical model है।',remember:'पहले situation को expression में model करो, फिर value रखो।',think:'अगर x=7 हो, तो 2(x+3) क्या देगा?'
},{title:'🔁 Chapter wrap-up',body:'अक्षर-संख्याओं वाले व्यंजक बदलने वाली quantities को represent करने का powerful तरीका हैं। Variable, constant, coefficient, substitution, patterns और expressions को real situations में जोड़कर गणितीय सोच मजबूत होती है।',remember:'Variable → Expression → Substitute → Calculate → Check।',exam:'Exam में expression बनाते समय words को operations में translate करो और final answer से पहले substitution/check करो।'}
],challenge:[
{question:'3x में 3 क्या है?',options:['Variable','Coefficient','Constant term only','Equation'],answer:1,explanation:'3, x का coefficient है क्योंकि यह x को 3 से गुणा दर्शाता है।',example:'यदि x=4, तो 3x=12।'},
{question:'x=5 हो तो 2x+3 का मान क्या है?',options:['10','13','15','8'],answer:1,explanation:'2(5)+3 = 10+3 = 13।',example:'5 tickets और ₹2 प्रति ticket की 2x जैसी लागत में fixed ₹3 जोड़ने जैसा सोचो।'},
{question:'“किसी संख्या का 4 गुना और 2 जोड़ो” का expression कौन-सा है?',options:['x+4+2','4x+2','4+x2','x/4+2'],answer:1,explanation:'4 गुना = 4x और फिर 2 जोड़ना = 4x+2।',example:'x=3 हो तो 4×3+2=14।'},
{question:'2x और x+2 में सही अंतर क्या है?',options:['दोनों हमेशा समान हैं','2x = 2×x, जबकि x+2 में 2 जोड़ा जाता है','2x का मतलब x+2 है','दोनों equations हैं'],answer:1,explanation:'Multiplication और addition अलग operations हैं।',example:'x=5 पर 2x=10, जबकि x+2=7।'},
{question:'यदि y=7 है, तो y−4 क्या होगा?',options:['11','28','3','−3'],answer:2,explanation:'7−4=3।',example:'₹7 में से ₹4 खर्च करने पर ₹3 बचते हैं।'},
{question:'2x+3 में x=0 हो तो answer क्या है?',options:['0','2','3','5'],answer:2,explanation:'2(0)+3 = 3।',example:'दोनों x-based items zero हों, फिर भी fixed 3 बचता है।'},
{question:'कौन-सा expression सही है यदि एक pen ₹8 का है और p pens खरीदे गए?',options:['8+p','8p','p−8','8/p'],answer:1,explanation:'p pens × ₹8 प्रति pen = 8p।',example:'5 pens की कीमत 8×5=₹40।'},
{question:'2x+5x का सरल रूप क्या है?',options:['7x','10x','7','2x²'],answer:0,explanation:'Same variable x वाले coefficients 2+5=7, इसलिए 7x।',example:'2 apples + 5 apples = 7 apples जैसा सोचो।'},
{question:'2x+3y को 5xy क्यों नहीं बनाया जा सकता?',options:['क्योंकि x और y अलग variables हैं','क्योंकि addition हमेशा multiplication है','क्योंकि coefficients नहीं होते','क्योंकि x और y numbers नहीं हैं'],answer:0,explanation:'Like terms के लिए variable part समान होना चाहिए।',example:'2 pens + 3 pencils को 5 pen-pencil नहीं कहा जा सकता।'},
{question:'यदि rectangle की लंबाई x और चौड़ाई 3 है तो perimeter क्या होगा?',options:['x+3','3x','2(x+3)','x+6'],answer:2,explanation:'Perimeter = 2(length+width) = 2(x+3)।',example:'x=7 पर perimeter 2(10)=20 units।'},
{question:'−2x में negative sign का क्या महत्व है?',options:['Ignore कर सकते हैं','यह coefficient को negative बनाता है','यह variable है','यह bracket है'],answer:1,explanation:'−2x को −2×x समझा जाता है।',example:'x=3 पर −2x = −6।'},
{question:'Expression और equation में मुख्य अंतर क्या है?',options:['Expression में equality जरूरी है','Equation में बराबर का relation होता है','Expression में numbers नहीं होते','Equation हमेशा एक variable रखती है'],answer:1,explanation:'Equation में = relation होता है; expression में जरूरी नहीं।',example:'3x+2 expression है; 3x+2=11 equation है।'}
]};