window.mathsChapter01={
 id:1,
 title:'हमारे आसपास बड़ी संख्याएँ',
 icon:'🔢',
 source:'NCERT Ganita Prakash 2026–27',
 goal:'बड़ी संख्याओं को पढ़ना, लिखना, स्थान-मूल्य समझना, भारतीय और अंतरराष्ट्रीय संख्या प्रणालियों को जोड़ना तथा वास्तविक जीवन की बड़ी संख्याओं पर तर्क करना।',
 sections:[
  {title:'🌟 बड़ी संख्याएँ हमारे आसपास',body:'जनसंख्या, किसी शहर की दूरी, पुस्तकालय में पुस्तकों की संख्या, किसी आयोजन में लोगों की संख्या या किसी देश की अर्थव्यवस्था जैसे contexts में बहुत बड़ी संख्याएँ दिखाई देती हैं। बड़ी संख्या को देखकर घबराने के बजाय उसे समूहों और स्थान-मूल्य के आधार पर समझना आसान है।',remember:'बड़ी संख्या को छोटे groups में बाँटकर पढ़ना आसान होता है।',think:'यदि 5,00,000 को 5 लाख कहा जा सकता है, तो 50,00,000 को किस नाम से कहोगे?'},
  {title:'🇮🇳 भारतीय संख्या पद्धति',body:'भारतीय संख्या पद्धति में इकाई, दहाई, सैकड़ा, हजार, दस हजार, लाख, दस लाख, करोड़ आदि स्थान आते हैं। संख्या लिखते समय commas का grouping भी इसी व्यवस्था के अनुसार किया जाता है। उदाहरण के लिए 12,34,567 को “बारह लाख चौंतीस हजार पाँच सौ सड़सठ” पढ़ा जाता है।',remember:'Indian grouping: 3 digits पहले, फिर हर group में 2 digits — 12,34,567।',visual:['1','10','100','1,000','1,00,000','1,00,00,000'],visualText:['इकाई','दहाई','सैकड़ा','हजार','लाख','करोड़']},
  {title:'🌍 अंतरराष्ट्रीय संख्या पद्धति',body:'International system में thousands, millions और billions जैसे groups उपयोग होते हैं। उदाहरण: 1,234,567 को 1 million से अधिक लेकिन 2 million से कम संख्या के रूप में समझा जा सकता है। Grouping का pattern अलग है, इसलिए comma placement पर ध्यान देना जरूरी है।',remember:'International grouping generally 3-3-3… होती है: 1,234,567।'},
  {title:'🧩 Place value का असली खेल',body:'किसी digit का value केवल उस digit पर निर्भर नहीं करता; उसकी position भी महत्वपूर्ण होती है। 5,00,000 में 5 का place value पाँच लाख है, जबकि 50,000 में वही digit पाँच दस हजार का value देता है।',remember:'Digit × उसका place = place value.',think:'7,05,004 में 5 का place value क्या होगा?'},
  {title:'🔎 Face value और place value',body:'Face value केवल digit की अपनी संख्या है। उदाहरण: 8,45,632 में 5 की face value 5 है, लेकिन उसकी place value 5,000 है। दोनों शब्दों को confuse नहीं करना चाहिए।',remember:'Face value = digit itself; Place value = digit की position से मिला value।'},
  {title:'✍️ बड़ी संख्या लिखना',body:'शब्दों में दी गई संख्या को digits में लिखते समय पहले बड़े groups सोचो, फिर हर group के अंदर सही places भरो। उदाहरण के लिए “सात लाख तीन हजार बारह” का numeric form 7,03,012 है। बीच के खाली places के लिए zero की जरूरत हो सकती है।',remember:'Words → groups पहचानो → missing places में 0 भरो → comma लगाओ।',mistake:'Common mistake: “7 लाख 3 हजार 12” को 7,31,2 जैसे गलत grouping में लिख देना। सही form 7,03,012 है।'},
  {title:'📖 बड़ी संख्या पढ़ना',body:'Reading करते समय commas को group separators की तरह देखो। 4,25,06,018 को 4 करोड़ 25 लाख 6 हजार 18 पढ़ा जा सकता है। जहाँ किसी group में leading zeros हों, वहाँ उन्हें अनावश्यक रूप से बोलना जरूरी नहीं।',remember:'पहले comma groups पहचानो, फिर left से right पढ़ो।'},
  {title:'⚖️ तुलना: कौन बड़ी?',body:'दो बड़ी संख्याओं की तुलना करने के लिए पहले उनके digits की कुल संख्या देखना उपयोगी है। समान digits हों, तो सबसे बाएँ digit से तुलना करते हुए आगे बढ़ो। 8,75,000 और 9,10,000 में 9 लाख वाली संख्या बड़ी है क्योंकि highest place पर 9 > 8।',remember:'Digits की संख्या → सबसे बाएँ place से comparison → पहला difference निर्णायक।'},
  {title:'➕ विस्तार रूप (Expanded Form)',body:'Expanded form किसी संख्या के हर digit का place-value contribution दिखाता है। 4,32,105 = 4,00,000 + 30,000 + 2,000 + 100 + 5। इससे zero वाले places और place value दोनों स्पष्ट होते हैं।',remember:'Expanded form = सभी non-zero place values का योग।',think:'6,04,020 को expanded form में लिखो।'},
  {title:'🔄 Indian ↔ International connection',body:'एक ही संख्या को दो systems में अलग नामों से व्यक्त किया जा सकता है। 1 crore = 10 million और 1 lakh = 100 thousand। Conversion करते समय actual value वही रहती है; केवल naming/grouping बदलती है।',remember:'Number का value same रहता है; system बदलने पर grouping/name बदलता है।'},
  {title:'💰 वास्तविक जीवन में estimation',body:'कभी exact number की जरूरत नहीं होती। उदाहरण के लिए, किसी stadium में 49,800 लोग हैं तो लगभग 50,000 कहना quick estimate हो सकता है। Estimation का उपयोग निर्णय और comparison को तेज़ बनाने में होता है, लेकिन exact calculation चाहिए तो approximate value को final answer नहीं मानना चाहिए।',remember:'Estimate = जल्दी समझने/तुलना करने के लिए लगभग मान।'},
  {title:'🧠 Number sense और reasoning',body:'बड़ी संख्याओं के साथ केवल पढ़ना-लिखना ही नहीं, बल्कि reason करना भी जरूरी है। यदि एक गाँव की population 24,500 है और दूसरे की 42,500, तो दूसरे में 18,000 ज्यादा लोग हैं। ऐसी तुलना daily-life data को समझने में मदद करती है।',remember:'Numbers → compare → calculate difference → interpret meaning।'},
  {title:'⚠️ Common mistakes & exam traps',body:'गलत comma placement, face value और place value को मिलाना, zeros छोड़ देना, Indian और international grouping को mix करना और estimate को exact answer मान लेना common mistakes हैं। हमेशा number की structure पहले जाँचो।',remember:'Comma placement + place value + zero positions = तीन सबसे जरूरी checks।',mistake:'Exam trap: 1,00,000 को one million मत समझो। एक लाख = 100,000; one million = 10,00,000।'},
  {title:'🎯 परीक्षा strategy',body:'Number-system question में पहले system पहचानो, फिर grouping देखो। अगर “place value” पूछा है तो digit की position बताओ; अगर “face value” पूछा है तो केवल digit बताओ। Conversion में units लिखो और अंतिम answer का magnitude sanity-check करो।',remember:'System → Grouping → Place → Value → Sanity check'},
  {title:'🔁 Chapter wrap-up',body:'बड़ी संख्याएँ डरावनी तभी लगती हैं जब उनकी structure न समझ आए। Indian और international systems में grouping अलग हो सकती है, लेकिन number का actual value वही रहता है। Place value, face value, expanded form, comparison, estimation और conversion की समझ number sense को मजबूत करती है।',remember:'देखो → group करो → place पहचानो → value समझो → compare/convert करो → answer जाँचो।'}
 ],
 challenge:[
  {question:'भारतीय संख्या पद्धति में 12,34,567 को कैसे पढ़ेंगे?',options:['बारह करोड़ चौंतीस हजार पाँच सौ सड़सठ','बारह लाख चौंतीस हजार पाँच सौ सड़सठ','एक करोड़ तेईस लाख पैंतालीस हजार छह सौ सात','एक लाख तेईस हजार पैंतालीस'],answer:1,explanation:'12,34,567 में groups 12 | 34 | 567 हैं, इसलिए यह बारह लाख चौंतीस हजार पाँच सौ सड़सठ है। उदाहरण: 10 लाख = 10,00,000।'},
  {question:'7,05,004 में 5 का place value क्या है?',options:['5','50','5,000','50,000'],answer:2,explanation:'5 हजार के स्थान पर है, इसलिए इसका place value 5,000 है। Face value केवल 5 होगी।'},
  {question:'8,45,632 में 5 की face value क्या है?',options:['5','500','5,000','50,000'],answer:0,explanation:'Face value digit की अपनी value होती है। 5 जहाँ भी हो, उसकी face value 5 ही रहती है।'},
  {question:'6,04,020 का expanded form कौन-सा है?',options:['6,00,000 + 4,000 + 20','6,00,000 + 40,000 + 20','6,000 + 400 + 20','6,00,000 + 400 + 20'],answer:0,explanation:'6 लाख + 4 हजार + 20 = 6,04,020। उदाहरण: zero वाले places का contribution 0 होता है, उन्हें छोड़ा जा सकता है।'},
  {question:'इनमें बड़ी संख्या कौन-सी है?',options:['8,75,000','9,10,000','दोनों बराबर','तय नहीं कर सकते'],answer:1,explanation:'दोनों में 6 digits हैं, इसलिए leftmost digit देखें: 9 > 8। इसलिए 9,10,000 बड़ी है।'},
  {question:'भारतीय संख्या पद्धति में 1,00,000 क्या है?',options:['एक हजार','एक लाख','दस लाख','एक करोड़'],answer:1,explanation:'1,00,000 = one lakh. Example: 10 लाख = 10,00,000।'},
  {question:'International grouping का सही उदाहरण कौन-सा है?',options:['12,34,567','1,234,567','1,23,45,67','123,45,67'],answer:1,explanation:'International system में digits को 3-3 के groups में बाँटा जाता है: 1,234,567।'},
  {question:'“सात लाख तीन हजार बारह” का सही numeric form कौन-सा है?',options:['7,31,200','7,03,012','7,30,012','7,003,12'],answer:1,explanation:'7 लाख = 7,00,000; 3 हजार = 3,000; 12 जोड़ने पर 7,03,012।'},
  {question:'1 crore का international value क्या है?',options:['1 million','10 million','100 million','1 billion'],answer:1,explanation:'1 crore = 10,000,000 = 10 million. नाम बदलता है, actual value नहीं।'},
  {question:'49,800 लोगों के लिए 50,000 कहना किसका उदाहरण है?',options:['Exact calculation','Estimation','Place value','Face value'],answer:1,explanation:'49,800 को लगभग 50,000 मानना estimation है। Exact count फिर भी 49,800 ही है।'},
  {question:'दो numbers में digits की संख्या बराबर हो तो तुलना कैसे शुरू करें?',options:['सबसे दाएँ digit से','सबसे बाएँ place से','केवल commas देखकर','Random digit चुनकर'],answer:1,explanation:'समान digit-count में highest place से तुलना शुरू करें। पहला अलग digit निर्णय करता है।'},
  {question:'कौन-सा कथन सही है?',options:['Face value position पर निर्भर करती है','Place value हमेशा digit के बराबर होती है','एक ही digit की face value वही रहती है, place value position पर बदलती है','Indian और international systems में number value बदल जाता है'],answer:2,explanation:'Face value digit itself है; place value position पर निर्भर करती है। इसलिए 5 की face value हमेशा 5, लेकिन अलग positions पर place value अलग होगी।'}
 ]
};