(function(){
'use strict';
const chapterKeys=['mathsChapter01','mathsChapter02','mathsChapter03','mathsChapter04','mathsChapter05','mathsChapter06','mathsChapter07','mathsChapter08'];
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function all(){return chapterKeys.map(k=>window[k]).filter(Boolean)}
function activeChapter(){const n=Number(new URLSearchParams(location.search).get('chapter'))||1;return all().find(c=>Number(c.id)===n)||all()[0]||null}
function corpus(){return all().flatMap(c=>(c.sections||[]).map(s=>({...s,chapterId:c.id,chapterTitle:c.title})))}
function findTopic(q){const t=String(q||'').toLowerCase();const units=t.split(/\s+/).filter(x=>x.length>2);return corpus().map(s=>{const hay=(s.title+' '+s.body+' '+(s.remember||'')+' '+(s.example||'')).toLowerCase();let score=0;units.forEach(u=>{if(hay.includes(u))score++});return{s,score}}).sort((a,b)=>b.score-a.score)[0]?.s||null}
function localFallback(q){const s=findTopic(q);if(!s)return '<p>यह सवाल मेरे local Maths content से बाहर है। AI Tutor connection उपलब्ध न हो तो बाद में फिर कोशिश करें।</p>';return `<div class="mt-context"><b>अध्याय ${s.chapterId} • ${esc(s.chapterTitle)}</b><span>${esc(s.title)}</span></div><p>${esc(s.body)}</p>${s.example?`<div class="mt-example"><b>🌍 उदाहरण:</b> ${esc(s.example)}</div>`:''}<div class="mt-callout"><b>💡 याद रखो:</b> ${esc(s.remember||'Concept को example से जोड़कर समझो।')}</div>`}
function ensure(){if(document.getElementById('mathsTutor'))return document.getElementById('mathsTutor');const w=document.createElement('div');w.id='mathsTutor';w.className='mt-widget';w.innerHTML=`<button class="mt-fab" aria-label="Maths Tutor खोलें">🤖</button><section class="mt-panel" hidden role="dialog" aria-label="Maths Tutor"><header><div><b>🤖 Maths Tutor</b><small>कक्षा 6 • गणित</small></div><button class="mt-close" aria-label="बंद करें">×</button></header><div class="mt-quick"><button data-q="इस concept को आसान भाषा में समझाओ">💡 समझाओ</button><button data-q="मुझे एक छोटा hint दो, पूरा answer नहीं">🧩 Hint</button><button data-q="एक आसान real-life example दो">🌍 Example</button><button data-q="step-by-step पूरा solution बताओ">🪜 Steps</button></div><div class="mt-msgs"><div class="mt-bot">नमस्ते! 😊 कोई भी Maths question पूछो। मैं exact answer, steps और जरूरत हो तो example दूँगा।</div></div><form class="mt-form"><input required maxlength="800" placeholder="जैसे: 27 × 37 पूरा तरीका समझाओ"><button>भेजें</button></form></section>`;document.body.appendChild(w);const panel=w.querySelector('.mt-panel'),msgs=w.querySelector('.mt-msgs'),input=w.querySelector('.mt-form input');w.querySelector('.mt-fab').onclick=()=>panel.hidden=!panel.hidden;w.querySelector('.mt-close').onclick=()=>panel.hidden=true;w.querySelectorAll('.mt-quick button').forEach(b=>b.onclick=()=>ask(b.dataset.q));w.querySelector('.mt-form').onsubmit=e=>{e.preventDefault();const q=input.value.trim();input.value='';ask(q)};
async function ask(text){if(!text)return;const user=document.createElement('div');user.className='mt-user';user.textContent=text;msgs.appendChild(user);const typing=document.createElement('div');typing.className='mt-bot mt-typing';typing.textContent='AI Tutor सोच रहा है…';msgs.appendChild(typing);msgs.scrollTop=msgs.scrollHeight;try{const AI=window.AITutorClient;if(!AI)throw new Error('AI client load नहीं हुआ');const c=activeChapter();const history=Array.from(msgs.children).filter(x=>!x.classList.contains('mt-typing')).slice(-10).map(x=>({role:x.classList.contains('mt-user')?'user':'assistant',content:x.textContent}));const answer=await AI.ask({messages:history.concat([{role:'user',content:text}]),subject:'Mathematics',chapter:c?.title||'',section:''});typing.remove();const bot=document.createElement('div');bot.className='mt-bot';bot.textContent=answer;msgs.appendChild(bot)}catch(err){typing.remove();const bot=document.createElement('div');bot.className='mt-bot';bot.innerHTML=localFallback(text);msgs.appendChild(bot);console.error('Maths Tutor AI error:',err)}msgs.scrollTop=msgs.scrollHeight}
return w}
window.MathsTutor={open:()=>{const w=ensure();w.querySelector('.mt-panel').hidden=false},ask:q=>{const w=ensure();w.querySelector('.mt-panel').hidden=false;w.querySelector('.mt-form input').value=q;w.querySelector('.mt-form').dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}))}};
})();
