(function(){
'use strict';
const chapters=['mathsChapter01','mathsChapter02','mathsChapter03','mathsChapter04','mathsChapter05','mathsChapter06','mathsChapter07','mathsChapter08'];
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function all(){return chapters.map(k=>window[k]).filter(Boolean)}
function corpus(){return all().flatMap(c=>(c.sections||[]).map(s=>({...s,chapterId:c.id,chapterTitle:c.title})));}
function detect(q){const t=String(q||'').toLowerCase();let type='explain';if(/hint|संकेत|अटक|help/.test(t))type='hint';else if(/example|उदाहरण|मिसाल/.test(t))type='example';else if(/step|चरण|हल|solve|solution|समाधान/.test(t))type='steps';else if(/गलत|mistake|error|गलती/.test(t))type='mistake';else if(/quiz|test|सवाल|प्रश्न/.test(t))type='quiz';return type}
function findTopic(q){const t=String(q||'').toLowerCase();const units=t.split(/\s+/).filter(x=>x.length>2);return corpus().map(s=>{const hay=(s.title+' '+s.body+' '+(s.remember||'')+' '+(s.example||'')).toLowerCase();let score=0;units.forEach(u=>{if(hay.includes(u))score+=1});return {s,score}}).sort((a,b)=>b.score-a.score)[0]?.s||null}
function fallback(type){const m={explain:'किसी भी गणित के सवाल का नाम/अध्याय लिखो; मैं concept को आसान भाषा में समझाऊँगा।',hint:'सवाल भेजो। पहले छोटा संकेत मिलेगा, पूरा उत्तर तुरंत नहीं।',example:'किस concept का example चाहिए? जैसे “place value का example दो।”',steps:'पूरा question भेजो। मैं उसे छोटे-छोटे verified steps में तोड़ूँगा।',mistake:'अपना किया हुआ step/answer भेजो; मैं बताऊँगा कि गलती किस प्रकार की है।',quiz:'किस chapter से quiz चाहिए, बताओ।'};return m[type]||m.explain}
function response(q){const type=detect(q),s=findTopic(q);if(!s)return {html:`<p>${esc(fallback(type))}</p>`};const intro=`<div class="mt-context"><b>अध्याय ${s.chapterId} • ${esc(s.chapterTitle)}</b><span>${esc(s.title)}</span></div>`;if(type==='example')return {html:intro+`<h4>🌍 उदाहरण</h4><p>${esc(s.example||'इस concept को एक छोटी वास्तविक स्थिति से जोड़कर सोचो।')}</p><div class="mt-callout"><b>💡 याद रखो:</b> ${esc(s.remember||s.body)}</div>`};if(type==='hint')return {html:intro+`<h4>🧩 पहला संकेत</h4><p>पहले question में दिए numbers, symbols या shapes को पहचानो। फिर पूछो: <b>“मुझसे क्या निकालने को कहा गया है?”</b></p><p class="mt-muted">Concept: ${esc(s.remember||s.body.slice(0,180))}</p>`};if(type==='mistake')return {html:intro+`<h4>🔎 गलती खोजने का तरीका</h4><p>${esc(s.mistake||'हर step को अलग जाँचो: calculation, sign, place value, operation और reasoning।')}</p><div class="mt-callout"><b>✅ Check:</b> ${esc(s.remember||'हर intermediate step को verify करो।')}</div>`};if(type==='steps')return {html:intro+`<h4>🪜 Step-by-step सोच</h4><ol><li>Question को छोटे हिस्सों में बाँटो।</li><li>${esc(s.remember||'पहले concept/rule पहचानो।')}</li><li>अब operation या relation लागू करो।</li><li>Answer का अनुमान लगाकर check करो।</li></ol><div class="mt-callout"><b>📘 Concept:</b> ${esc(s.body)}</div>`};if(type==='quiz')return {html:intro+`<h4>🎯 Mini Quiz</h4><p>इसी concept पर question बनाओ और पहले खुद answer दो:</p><div class="mt-question">${esc(s.think||s.activity||s.example||'इस concept का अपना example बनाओ।')}</div>`};return {html:intro+`<p>${esc(s.body)}</p>${s.example?`<div class="mt-example"><b>🌍 उदाहरण:</b> ${esc(s.example)}</div>`:''}<div class="mt-callout"><b>💡 याद रखो:</b> ${esc(s.remember||'Concept को example से जोड़कर समझो।')}</div>`}}
function ensure(){if(document.getElementById('mathsTutor'))return document.getElementById('mathsTutor');const w=document.createElement('div');w.id='mathsTutor';w.className='mt-widget';w.innerHTML=`<button class="mt-fab" aria-label="Maths Tutor खोलें">🤖</button><section class="mt-panel" hidden role="dialog" aria-label="Maths Tutor"><header><div><b>🤖 Maths Tutor</b><small>कक्षा 6 • गणित</small></div><button class="mt-close" aria-label="बंद करें">×</button></header><div class="mt-quick"><button data-q="explain">💡 समझाओ</button><button data-q="hint">🧩 Hint</button><button data-q="example">🌍 Example</button><button data-q="steps">🪜 Steps</button></div><div class="mt-msgs"><div class="mt-bot">नमस्ते! 😊 Maths का question भेजो। मैं final answer से पहले तुम्हें सोचने और steps समझने में मदद करूँगा।</div></div><form class="mt-form"><input required maxlength="500" placeholder="जैसे: 2x + 3 में x=5 हो तो कैसे हल करें?"><button>भेजें</button></form></section>`;document.body.appendChild(w);const panel=w.querySelector('.mt-panel'),msgs=w.querySelector('.mt-msgs');w.querySelector('.mt-fab').onclick=()=>panel.hidden=!panel.hidden;w.querySelector('.mt-close').onclick=()=>panel.hidden=true;w.querySelectorAll('.mt-quick button').forEach(b=>b.onclick=()=>{const label=b.dataset.q;const prompts={explain:'इस concept को आसान भाषा में समझाओ',hint:'मुझे hint दो',example:'एक आसान example दो',steps:'step-by-step तरीका बताओ'};ask(prompts[label])});w.querySelector('.mt-form').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');ask(input.value);input.value=''};function ask(text){const user=document.createElement('div');user.className='mt-user';user.textContent=text;msgs.appendChild(user);const bot=document.createElement('div');bot.className='mt-bot';bot.innerHTML=response(text).html;msgs.appendChild(bot);msgs.scrollTop=msgs.scrollHeight}return w}
window.MathsTutor={open:()=>{const w=ensure();w.querySelector('.mt-panel').hidden=false},ask:q=>{const w=ensure();w.querySelector('.mt-panel').hidden=false;w.querySelector('.mt-form input').value=q;w.querySelector('.mt-form').dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}))}};
})();